/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Achievement Gotten!": "成就达成！",
    "(it's all really good)": "（一切都很好）",
    "% complete": "％ 完成",
    "Continue": "继续",
    "Cost:": "成本：",
    "Enable music and SFX?": "启用音乐和 SFX？",
    "Loading": "正在加载",
    "Start over": "重来",
    "This Game Is Haunted": "这个游戏闹鬼",
    "You can enable or disable audio in the options menu at any time": "您可以随时在选项菜单中启用或禁用音频",
    "You need to enable JavaScript to run this app.": "您需要启用 JavaScript 才能运行此应用程序。",
    "– Day": "– 天",
    "A human is mad": "一个人疯了",
    "Across the back lawn": "穿过后草坪",
    "Act": "行为",
    "Act I": "第一幕",
    "And they're making a terrible bang": "他们正在发出可怕的爆炸声",
    "And when you next look around": "当你下次环顾四周时",
    "Autosave": "自动保存",
    "Back to Title Screen": "返回标题屏幕",
    "Dialogue Speed:": "对话速度：",
    "Food": "食物",
    "Game Paused": "游戏暂停",
    "Gather Food": "收集食物",
    "Gather Trash": "收集垃圾",
    "Global Business Level:": "全球业务水平：",
    "Hold": "抓住",
    "How to Gather Trash and Influence Raccoons": "如何收集垃圾和影响浣熊",
    "In your search, you find some trash. Its appeal is undeniable.": "在您的搜索中，您会发现一些垃圾。它的吸引力是不可否认的。",
    "in-game to view keyboard controls (where available)": "在游戏中查看键盘控制（如果可用）",
    "Jobs": "工作",
    "Level": "等级",
    "Load": "加载",
    "Medium": "中等",
    "Music:": "音乐：",
    "Off": "关",
    "On": "开",
    "or": "或",
    "Our treasure. No bin, can, or dumpster is safe.": "我们的宝藏。没有垃圾桶、罐头或垃圾箱是安全的。",
    "Press": "按",
    "Raccoons assigned": "分配的浣熊",
    "reached...": "到达...",
    "Scared by the human's big sound": "被人类的大声音吓到了",
    "SFX:": "音效：",
    "Show teeth, rip and gnash": "显示牙齿，撕裂和咬牙切齿",
    "Sort Trash": "分类垃圾",
    "Take off in a dash": "快速起飞",
    "Tense and Trashy": "紧张和垃圾",
    "That you're near their pad": "你在他们的垫子附近",
    "The good stuff.": "好东西。",
    "The human is holding their ground": "人类坚守阵地",
    "to open/close the Options screen": "打开/关闭选项屏幕",
    "To snatch trash, but suddenly: CLANG": "抢垃圾，但突然：叮当",
    "Toggle Full Screen": "切换全屏",
    "Trash": "垃圾",
    "unassigned": "未分配",
    "Volume:": "音量：",
    "What does this crisis demand?": "这场危机需要什么？",
    "With cutie panache": "带着可爱的华丽",
    "You act in a flash": "你一闪而过",
    "You approach the cans with the gang": "你和那帮人一起接近罐头",
    "You consider the options at hand": "您考虑手头的选择",
    "You put it in your mouth and then digest it.": "你把它放在嘴里，然后消化它。",
    "You're the leader of a group of raccoons looking for food to survive.": "你是一群浣熊寻找食物生存的领导者。",
    "Your friends are all gone": "你的朋友都走了",
    "As you gather more trash, you start naturally sorting it by type.": "随着您收集更多垃圾，您自然会开始按类型对其进行分类。",
    "Bones": "骨头",
    "Cloth": "布",
    "Do-it-yourself xylophone kit.": "自己动手做的木琴套件。",
    "Eating food rules, so get enough for everybody.": "饮食规则，所以每个人都吃饱。",
    "Full of the complex smell of human expression.": "充满了人类表情的复杂气味。",
    "Hats, airplanes, cuts, subpoenas — there's nothing you can't make outta this stuff.": "帽子、飞机、剪裁、传票——没有什么是你做不到的。",
    "It's like rock but a little bit more upset.": "这就像摇滚，但有点心烦意乱。",
    "It's the gang. Right now, 5 out of 5 are doing stuff, and 0 are chilling. New raccoons arrive in 16 seconds.": "是帮派 现在，五分之五的人在做事，0 人在发冷。 新浣熊在 16 秒内到达。",
    "It's the gang. Right now, 5 out of 5 are doing stuff, and 0 are chilling. New raccoons won't join until you've got food saved up and a well-sorted trash pile.": "是帮派 现在，五分之五的人在做事，0 人在发冷。 新浣熊不会加入，除非你有食物储备和分类良好的垃圾堆。",
    "Lasts forever. Couldn't possibly cause any problems down the line.": "永远持续下去。 不可能导致任何问题。",
    "Metal": "金属",
    "Paper": "纸",
    "Plastic": "塑料",
    "Portable tree essence.": "便携树精。",
    "Raccoons": "浣熊",
    "Time to take out the trash...and place it neatly into discrete piles.": "是时候把垃圾拿出来了……把它整齐地堆成一堆。",
    "Time Until Raccoons Eat": "浣熊吃东西的时间",
    "Wood": "木头",
    "Okey dokey": "好吧，好吧",
    "The human is shocked by your stand": "人类被你的立场震惊了",
    "And you're feeling rude": "你感觉很粗鲁",
    "Another bountiful cache": "另一个丰富的缓存",
    "But you're a clean dude": "但你是个干净的家伙",
    "But you're not in the mood": "但你没心情",
    "Cloud Cleaning": "云清扫",
    "Corn dogs for years": "多年来的玉米狗",
    "He dumps some new trash": "他倒了一些新垃圾",
    "It could be good food": "这可能是很好的食物",
    "Near a carnival dumpster with friends": "和朋友一起在嘉年华垃圾箱附近",
    "Now everyone pokes at the fluff": "现在每个人都在戳绒毛",
    "The feasting seems like it won't end": "盛宴似乎不会结束",
    "Then a worker comes into your sight": "然后一个工人进入你的视线",
    "This sure is mysterious stuff": "这肯定是神秘的东西",
    "This trash is a glorious blend": "这种垃圾是一种光荣的混合",
    "Time Until New Raccoons Arrive": "新浣熊到来的时间",
    "With a new treat that's so pink and light": "有了一种粉红色和轻盈的新款待",
    "Word of your well-sorted trash pile spreads. Your group of raccoons is growing.": "您分类良好的垃圾堆的消息传播开来。 你的浣熊群正在增长。",
    "You eat elephant ears": "你吃大象耳朵",
    "You gobble to show you're so tough": "你狼吞虎咽地表明你很坚强",
    "Your friends make a toast to the night": "你的朋友们为夜晚干杯",
    "Act II": "第二幕",
    "Advanced Stealing": "高级偷窃",
    "Animal Nature": "动物性质",
    "Apparently those noises they make actually mean something? Huh. Go figure.": "显然，他们发出的那些声音实际上意味着什么？嗯。去搞清楚。",
    "Attracts larger crowds of wandering raccoons to join your society.": "吸引更多的流浪浣熊加入你的社会。",
    "Book House": "书屋",
    "Build": "建造",
    "Build Queue": "建造队列",
    "Burying Food": "埋葬食物",
    "Counterfeiting Money": "伪造货币",
    "Detritus Ex Machina": "Detritus Ex Machina",
    "Develop the science of studying humans, the creators of the trash source.": "发展研究人类的科学，人类是垃圾源的创造者。",
    "Earn more resources when sorting trash.": "分类垃圾时赚取更多资源。",
    "Hands full of sweet treats": "满手甜食",
    "Human Language": "人类语言",
    "Human Studies": "人类研究",
    "Humans print this stuff all the time and then they use it to get more stuff. Seems pretty harmless.": "人类一直在打印这些东西，然后他们用它来获取更多的东西。看起来很无害。",
    "Humans spend most of their lives inside of specially constructed boxes. We, too, can dream such dreams.": "人类大部分时间都在特制的盒子里度过。我们也可以做这样的梦。",
    "Increases job efficiency.": "提高工作效率。",
    "Increases trash collection.": "增加垃圾收集。",
    "Label Maker": "标签机",
    "Live in decorative features": "生活在装饰特色",
    "No research in progress": "没有进行中的研究",
    "No research is in progress.": "没有研究正在进行中。",
    "Nothin' in the queue.": "队列中没有任何内容。",
    "Nothin'.": "没什么。",
    "Now you can prove things, even if no one believes you.": "现在你可以证明事情，即使没有人相信你。",
    "One day while out far on a lark": "有一天，远在云雀上",
    "Promise capture won't last": "承诺捕获不会持续",
    "Put some wheels on an old washing machine and just load that sucker up with trash.": "在旧洗衣机上装上一些轮子，然后把垃圾装满那个吸盘。",
    "Raccoon Boxes": "浣熊盒",
    "Requires:": "要求：",
    "Research": "研究",
    "Research Advanced Stealing": "研究高级窃取",
    "Signal ownership over friend and foe alike by sticking labels to them.": "通过给他们贴上标签来表明对朋友和敌人的所有权。",
    "Speeds up building.": "加快建设。",
    "Speeds up trash sorting.": "加快垃圾分类。",
    "Stuff old food in the ground, put some water on it, and even more food comes out. Works with pretty much all food.": "把旧食物塞进地里，在上面放点水，就会有更多的食物出来。适用于几乎所有食物。",
    "The Scientific Method": "科学方法",
    "The stock market is basically just a giant trashcan you can pull value from whenever you want.": "股市基本上只是一个巨大的垃圾桶，你可以随时从中获取价值。",
    "Their caged lives seem rather dark": "他们笼中的生活似乎相当黑暗",
    "They point and laugh, flinging their spit": "他们指指点点大笑，吐唾沫",
    "They taunt the great beasts": "他们嘲弄巨兽",
    "This is like a house for raccoons, except only books live here. This is how a civilized society shows respect for books.": "这就像一个浣熊的房子，除了这里只有书。这就是文明社会对书籍的尊重。",
    "This whole scene has you in a fit": "这整个场景让你合不拢嘴",
    "Time to complete: 0:15": "完成时间：0:15",
    "Time to complete: 0:30": "完成时间：0:30",
    "Trash Carrier": "垃圾车",
    "Try to ask the cat out but fall flat": "试着约猫出去，但结果一落千丈",
    "Unlocks building farms. Farms increase the amount of food gathered.": "解锁建筑农场。农场增加了收集的食物量。",
    "Unlocks building shelters. Each shelter increases the maximum number of raccoons by 20.": "解锁建筑庇护所。每个庇护所都会增加 20 只浣熊的最大数量。",
    "Unlocks the next act.": "解锁下一幕。",
    "Unlocks the rest of the research options.": "解锁其余的研究选项。",
    "Where big, wild creatures": "哪里有大型的野生动物",
    "With a nearby striped, mighty cat": "附近有一只条纹强大的猫",
    "You also see kids, little twits": "你也看到孩子们，小笨蛋",
    "You decide that you'll have a chat": "您决定聊天",
    "You find something particularly special in a recent batch of trash.": "你在最近的一批垃圾中发现了一些特别的东西。",
    "You stumble on a new type of park": "你偶然发现了一种新型公园",
    "You walk up to the glass": "你走到玻璃前",
    "You're a rude bag of gas": "你是一个粗鲁的汽油袋",
    "You're in love, talking fast": "你恋爱了，说话很快",
    "Breaking news! I’ve been studying humans and I’ve noticed that they say things like “Breaking news!” to get attention. That’s just one of the valuable lessons I’ve learned. I think it might be worth setting up a permanent way to research them.": "爆炸新闻！ 我一直在研究人类，我注意到他们会说“突发新闻！”之类的话。 引起注意。 这只是我学到的宝贵经验之一。 我认为建立一种永久的方法来研究它们可能是值得的。",
    "Hey everyone! I know we’ve all recently become aware of ourselves, learned to read and write, and have started constructing rudimentary shelters. It’s a lot. But I wanted to post this up and let everyone know that it’s OK to just chill. Changing your entire conception of self and society is a lot to go through, so it’s totally valid to take some time for yourself.": "嘿大家！ 我知道我们最近都意识到了自己，学会了阅读和写作，并开始建造简陋的避难所。 很多。 但我想把它贴出来，让大家知道放松一下是可以的。 改变你对自我和社会的整个概念需要经历很多事情，所以为自己花点时间是完全有效的。",
    "Completed: Human Studies": "完成：人类研究",
    "Emergency Bulletin": "紧急公告",
    "Human Studies ✔️": "人类研究✔️",
    "Message board unlocked.": "留言板解锁。",
    "There isn't enough trash to sort! Go get some trash first.": "没有足够的垃圾分类！ 先去捡垃圾吧。",
    "We Live in a Society": "我们生活在一个社会中",
    "What comes next may shock you: haha, sorry just practicing.": "接下来的事情可能会让你大吃一惊：哈哈，抱歉刚刚练习。",
    "You now understand the complex cocktail of emotions that these poor, hairless creatures possess.": "你现在明白了这些可怜的、无毛的生物所拥有的复杂的情感混合物。",
    "Exciting New Food from the Ground": "来自地面的令人兴奋的新食物",
    "Farm": "农场",
    "Increases the amount of food gathered.": "增加收集的食物量。",
    "It's upsetting to pull food out of the earth instead of the trash, but we're adjusting.": "将食物而不是垃圾从地球中取出是令人不安的，但我们正在调整。",
    "Looking for someone to trade some sub sandwiches, which are food I can eat, for a large collection of golden dubloons, which are pirate treasure and rather inedible. Thanks for your consideration.": "找人交换一些三明治，这是我可以吃的食物，大量的黄金达布隆，这是海盗宝藏，相当不可食用。 感谢您的考虑。",
    "Not currently building anything.": "目前没有建造任何东西。",
    "Some more raccoons are coming this way! They'll be here in 1 second. Make sure there's enough space available for them to settle in.": "更多的浣熊正朝这边来！ 他们会在 1 秒内到这里。 确保有足够的空间供他们安顿下来。",
    "Subs Not Dubs": "潜艇不是配音",
    "What once was dead lives yet again. Food necromancy rules.": "曾经死去的东西又复活了。 食物死灵法则。",
    "You can now build Farms": "您现在可以建造农场",
    "Building speed is reduced due to a food shortage. Gather more food for your raccoons!": "由于食物短缺，建筑速度降低。 为你的浣熊收集更多食物！",
    "Your raccoons are too hungry to research at a normal speed. Gather more food!": "你的浣熊太饿了，无法以正常速度进行研究。 收集更多食物！",
    "Your raccoons are too hungry to work at a normal speed. Gather more food!": "你的浣熊太饿了，无法以正常速度工作。 收集更多食物！",
    "A bold improvement on what humans call \"cars.\"": "对人类所谓的“汽车”的大胆改进。",
    "Cancel building this farm to refund the purchase cost of  50 bones and 50 cloth.": "取消建造这个农场，返还50块骨头和50块布的购买成本。",
    "Comes with one (1) \"Bless this Mess\" welcome mat.": "随附一 (1) 个“祝福这个混乱”欢迎垫。",
    "Don't let yourself get boxed in by old, detoriating cardboard. Introducing: a box for the modern lifestyle.": "不要让自己被陈旧的、变形的纸板困住。介绍：现代生活方式的盒子。",
    "Give Us Shelter": "给我们庇护",
    "Idea of Man Looking for Idea of Woman": "男人的想法寻找女人的想法",
    "Increases the maximum number of raccoons who can join your crew.": "增加可以加入您的船员的浣熊的最大数量。",
    "It’s like :0 and then it’s like :) hahahahha u know what I mean?!?!": "就像 :0 然后就像 :) haha​​hahha 你知道我的意思吗？！？！",
    "Me, a raccoon in a stunning blonde wig, red dress, and expertly repaired heels.": "我是一只浣熊，戴着漂亮的金色假发，穿着红色连衣裙，脚跟修得精巧。",
    "Meet me under the big branch at the back of the tree. I must perform the awful gender play of the humans. I crave their pain.": "在树后的大树枝下见我。我必须表演人类可怕的性别游戏。我渴望他们的痛苦。",
    "More raccoons will join periodically": "更多浣熊将定期加入",
    "No more pointing at restaurant menus while looking up at the waiter with an expression of polite contrition.": "不再指着餐厅的菜单，同时用礼貌的忏悔表情看着服务员。",
    "Party at Landfill": "垃圾填埋场派对",
    "Shelter": "庇护所",
    "tfw u tip the trash can over": "tfw你把垃圾桶翻过来",
    "Trash collection increased": "垃圾收集增加",
    "You can now build Shelters": "您现在可以建造庇护所",
    "You, a raccoon in a fedora (preferably few holes) and a decent-smelling trench coat. Maybe you found a pipe or a broken toy gun around.": "你，一只戴着软呢帽的浣熊（最好是几个洞）和一件闻起来像样的风衣。也许你在周围发现了一根管子或一把坏掉的玩具枪。",
    "Beakers! Flasks! Burners! Fashion!": "烧杯！烧瓶！燃烧器！时尚！",
    "Building speed increased": "建造速度增加",
    "Easy to make and free of consequence, just like a fire.": "易于制作且没有后果，就像火一样。",
    "Going on vacation to a different tree soon, but I’ve noticed that when I leave a lot of my paper and plastic trash gets blown away. Looking for someone to sit on my trash while I’m gone. You can have some of the trash, but not all of it.": "很快要去另一棵树度假，但我注意到当我留下很多纸和塑料垃圾时，会被吹走。我不在的时候找人坐在我的垃圾桶上。你可以有一些垃圾，但不是全部。",
    "I warned you it was my worst desire!!": "我警告过你这是我最坏的愿望！！",
    "I'm looking for a powerful potion that can help me fulfill my worst desires. What are they, you ask? Oh, you didn't ask? Well...would you like to hear them anyway? Keep reading!": "我正在寻找一种强大的药水，可以帮助我满足我最坏的愿望。你问他们是什么？哦，你没问？嗯……你想听听他们的声音吗？继续阅读！",
    "Jobs now take less time to perform.": "作业现在需要更少的时间来执行。",
    "Lost my hahahaha shut up wallet": "丢了我的哈哈哈哈闭嘴钱包",
    "Me, a person, hahahaha dude STOP was walking around on only two legs. My dumb brain could not keep track of my powerful paper holder, the wallet hahahaha and I lost it.": "我，一个人，哈哈哈哈老兄STOP只用两条腿走来走去。我的愚蠢大脑无法跟踪我强大的纸夹，钱包哈哈哈，我把它弄丢了。",
    "Mmm, yes. Wonderful. Consent is an important part of any interaction. So, what I want is a potion that will help me pop a pimple so hard that I fall over.": "嗯，是的。精彩的。同意是任何互动的重要组成部分。所以，我想要的是一种药水，它可以帮助我把一个疙瘩挤得那么厉害，以至于我摔倒了。",
    "Must have 3-5 years of sitting experience. LARGE BUTTS only. I have been blessed with a lot of trash.": "必须有3-5年的坐姿经验。仅限大屁股。我很幸运有很多垃圾。",
    "Oh my god I can’t do this anymore hahaha holy crap WOW. I know I know it’s too good. Did you get all of that down? Why are you still writing? Ok, just stop and post whatever you’ve got.": "哦，天哪，我不能再这样做了，哈哈哈，天哪，哇。我知道我知道这太好了。你把这一切都记下来了吗？为什么还在写？好吧，停下来张贴你所拥有的一切。",
    "Please find my wallet!! Otherwise I cannot exercise my power as a tall, nearly hairless mammal!": "请找到我的钱包！！否则我无法发挥我作为一个高大、几乎没有毛的哺乳动物的力量！",
    "Powerful Potions": "强力药水",
    "THIS POP-UP IS PROPERTY OF RACCOON. IF FOUND, PLEASE RETURN TO RACCOON.": "这个弹出窗口是 Raccoon 的财产。如果找到，请返回 RACCOON。",
    "Trash Sitters Wanted": "垃圾保姆通缉",
    "Trash sorting yield increased": "垃圾分类收率提高",
    "Yes...come closer to this note, stranger...mmm, perfect.": "是的……靠近这张纸条，陌生人……嗯，完美。",
    "Ah, finally! Nothing to do now but put these cool sunglasses on my face and read these books *drops glasses* oh no": "啊，终于！ 现在无事可做，只好把这些酷酷的太阳镜戴在我脸上读这些书*戴眼镜*哦不",
    "Anyone seen any baby shoes around? I don’t care if they’re used or not, I just love the dang things. Hit me up! - Ernest": "有人看到附近有婴儿鞋吗？ 我不在乎它们是否被使用，我只是喜欢那些该死的东西。 打我！ - 欧内斯特",
    "Baby Shoes": "婴儿鞋",
    "My (3R) partner (3R) and I are looking for trash. Please contact us if you have trash. All trash considered. No non-trash bartering.": "我的 (3R) 伙伴 (3R) 和我正在寻找垃圾。 如果您有垃圾请联系我们。 所有垃圾都考虑在内。 没有非垃圾易货交易。",
    "tl;dr: looking for some trash thanks": "tl;博士：寻找一些垃圾谢谢",
    "Trash sorting efficiency increased": "垃圾分拣效率提高",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "Looking for some other self-motivated and self-actualized raccoons to gather boxes from the trash sortings to build houses. Everyone wants them! So I think it would be nice and fun to build them for everyone. I have seen humans do this and then drink from cans to celebrate. Let’s plan to drink from cans afterwards.": "寻找其他一些自我激励和自我实现的浣熊，从垃圾分类中收集盒子来建造房屋。 每个人都想要他们！ 所以我认为为每个人构建它们会很有趣。 我见过人类这样做，然后从罐头里喝水庆祝。 让我们计划之后用罐头喝。",
    "We've finally cleared the landfill closest to the trees! Having a raging party there tonight, just like we used to have. Bring your own food and trash. We’ve got a lot of chips, maybe bring some desserts I guess? Or drinks or whatever. We’re just happy to have you! Don’t forget your party attitude, wooo! Randy, disregard this message.": "我们终于清除了离树木最近的垃圾填埋场！ 今晚在那里举行一场盛大的派对，就像我们以前一样。 自带食物和垃圾。 我们有很多薯条，也许我想带些甜点吧？ 或者饮料什么的。 我们很高兴有你！ 不要忘记你的派对态度，哇！ 兰迪，忽略这条信息。",
    "Anyway, I think we should all get together and bury more food and see what happens. Maybe we could even section out some unused land specifically for this purpose. My mind is really buzzing with ideas. I’d love for someone to just come hang out by my food growths and chat with me about all of this.": "不管怎样，我认为我们都应该聚在一起，埋下更多的食物，看看会发生什么。 也许我们甚至可以专门为此目的划出一些未使用的土地。 我的脑海里真的充满了想法。 我很想有人来看看我的食物生长情况，和我聊聊这一切。",
    "This is an announcement for all raccoons in the community. Last Saturday, as I was messing around burying stuff for fun, I noticed that some of the food I buried a while ago was growing something. Get this, it was growing NEW FOOD! I know, right?!!": "这是社区中所有浣熊的公告。 上周六，当我为了好玩而到处埋东西时，我注意到我前一段时间埋的一些食物正在长出一些东西。 得到这个，它正在生长新的食物！ 我知道，对吧？！！",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "© 2019–2021": "© 2019–2021",
    "Y": "Y",
    "v2.1.0": "v2.1.0",
    "o": "o",
    "N": "N",
    "es": "",
    "Ctrl": "Ctrl",
    "X": "X",
    "Option": "Option",
    "Tab": "Tab",
    "F": "F",
    "E": "E",
    "Q": "Q",
    "R": "R",
    "S": "S",
    "T": "T",
    "TK": "TK",
    "W": "W",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "\n": "\n",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "Save File ": "保存文件 ",
    "Completed: ": "已完成: ",
    "Cancel Build: ": "取消建造: ",
    "Cooldown – ": "冷却 – ",
    "Active – ": "激活中 – ",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    " remaining": " 剩余",
    " items in queue": " 物品在队列中",
    " ✔️": " ✔️",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^\$([\d\.]+)$/,
    /^\+\$([\d\.]+)$/,
    /^\-\$([\d\.]+)$/,
    /^\+\$([\d\.]+)K$/,
    /^\-\$([\d\.]+)K$/,
    /^\$([\d\.]+)K$/,
    /^\(([\d\.]+)\/([\d\.]+)\)$/,
    /^成本(.+)$/,
    /^\(([\d\.]+)\%\)$/,
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) of these.$/, '你有 $1 这个。'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^You own (.+) out of (.+) shares \((.+) market share\).$/, '您拥有 $1 \/ $2 股（$3 的市场份额）。'],
    [/^Your (.+) raccoons will eat (.+) food in (.+) second. Make sure you have enough food on hand. Hungry raccoons can't work quickly and new raccoons won't join a community that has no food.$/, '你的 $1 只浣熊将在 $3 秒内吃掉 $2 食物。 确保手头有足够的食物。 饥饿的浣熊不能快速工作，新的浣熊不会加入没有食物的社区。'],
    [/^Your (.+) raccoons will eat (.+) food in (.+) seconds. Make sure you have enough food on hand. Hungry raccoons can't work quickly and new raccoons won't join a community that has no food.$/, '你的 $1 只浣熊将在 $3 秒内吃掉 $2 食物。 确保手头有足够的食物。 饥饿的浣熊不能快速工作，新的浣熊不会加入没有食物的社区。'],
    [/^It's the gang. Right now, ([\d\.]+) out of ([\d\.]+) are doing stuff, and ([\d\.]+) are chilling. New raccoons arrive in ([\d\.]+) seconds.$/, '这是帮派。现在，$1 \/ $2 的人在做事情，而 $3 人则令人毛骨悚然。新的浣熊在 $4 秒内到达。'],
    [/^Some more raccoons are coming this way! They'll be here in (\d+) seconds. Make sure there's enough space available for them to settle in.$/, '更多的浣熊正朝这边来！ 他们将在 $1 秒内到达。 确保有足够的空间供他们安顿下来。'],
    [/^\+(\d+) raccoons arrived$/, '\+$1 浣熊到达'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
    [/^Recruit (.+) Raccoons$/, '招募 $1 只浣熊'],
	[/^Scenario (\d+) of (\d+)$/, '场景 $1 \/ $2'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);