/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Achievement Gotten!": "成就达成！",
    "(it's all really good)": "（一切都很好）",
    "% complete": "％ 完成",
    "Continue": "继续",
    "Cost:": "成本：",
    "Enable music and SFX?": "启用音乐和音效？",
    "Loading": "正在加载",
    "Start over": "重来",
    "This Game Is Haunted": "这个游戏闹鬼",
    "You can enable or disable audio in the options menu at any time": "您可以随时在选项菜单中启用或禁用音频",
    "You need to enable JavaScript to run this app.": "您需要启用 JavaScript 才能运行此应用程序。",
    "– Day": "– 天",
    "A human is mad": "一个人疯了",
    "Across the back lawn": "穿过后草坪",
    "Act": "行为",
    "Act I": "第一幕",
    "And they're making a terrible bang": "他们正在发出可怕的爆炸声",
    "And when you next look around": "当你下次环顾四周时",
    "Autosave": "自动保存",
    "Back to Title Screen": "返回标题屏幕",
    "Dialogue Speed:": "对话速度：",
    "Food": "食物",
    "Game Paused": "游戏暂停",
    "Gather Food": "收集食物",
    "Gather Trash": "收集垃圾",
    "Global Business Level:": "全局业务等级：",
    "Hold": "抓住",
    "How to Gather Trash and Influence Raccoons": "如何收集垃圾和影响浣熊",
    "In your search, you find some trash. Its appeal is undeniable.": "在您的搜索中，您会发现一些垃圾。它的吸引力是不可否认的。",
    "in-game to view keyboard controls (where available)": "在游戏中查看键盘控制（如果可用）",
    "Jobs": "工作",
    "Level": "等级",
    "Load": "加载",
    "Medium": "中等",
    "Music:": "音乐：",
    "Off": "关",
    "On": "开",
    "or": "或",
    "Our treasure. No bin, can, or dumpster is safe.": "我们的宝藏。没有垃圾桶、罐头或垃圾箱是安全的。",
    "Press": "按",
    "Raccoons assigned": "分配的浣熊",
    "reached...": "到达...",
    "Scared by the human's big sound": "被人类的大声音吓到了",
    "SFX:": "音效：",
    "Show teeth, rip and gnash": "显示牙齿，撕裂和咬牙切齿",
    "Sort Trash": "分类垃圾",
    "Take off in a dash": "快速起飞",
    "Tense and Trashy": "紧张和垃圾",
    "That you're near their pad": "你在他们的垫子附近",
    "The good stuff.": "好东西。",
    "The human is holding their ground": "人类坚守阵地",
    "to open/close the Options screen": "打开/关闭选项屏幕",
    "To snatch trash, but suddenly: CLANG": "抢垃圾，但突然：叮当",
    "Toggle Full Screen": "切换全屏",
    "Trash": "垃圾",
    "unassigned": "未分配",
    "Volume:": "音量：",
    "What does this crisis demand?": "这场危机需要什么？",
    "With cutie panache": "带着可爱的华丽",
    "You act in a flash": "你一闪而过",
    "You approach the cans with the gang": "你和那帮人一起接近罐头",
    "You consider the options at hand": "您考虑手头的选择",
    "You put it in your mouth and then digest it.": "你把它放在嘴里，然后消化它。",
    "You're the leader of a group of raccoons looking for food to survive.": "你是一群浣熊寻找食物生存的领导者。",
    "Your friends are all gone": "你的朋友都走了",
    "As you gather more trash, you start naturally sorting it by type.": "随着您收集更多垃圾，您自然会开始按类型对其进行分类。",
    "Bones": "骨头",
    "Cloth": "布",
    "Do-it-yourself xylophone kit.": "自己动手做的木琴套件。",
    "Eating food rules, so get enough for everybody.": "饮食规则，所以每个人都吃饱。",
    "Full of the complex smell of human expression.": "充满了人类表情的复杂气味。",
    "Hats, airplanes, cuts, subpoenas — there's nothing you can't make outta this stuff.": "帽子、飞机、剪裁、传票——没有什么是你做不到的。",
    "It's like rock but a little bit more upset.": "这就像摇抽取，但有点心烦意乱。",
    "It's the gang. Right now, 5 out of 5 are doing stuff, and 0 are chilling. New raccoons arrive in 16 seconds.": "是帮派 现在，五分之五的人在做事，0 人在发冷。 新浣熊在 16 秒内到达。",
    "It's the gang. Right now, 5 out of 5 are doing stuff, and 0 are chilling. New raccoons won't join until you've got food saved up and a well-sorted trash pile.": "是帮派 现在，五分之五的人在做事，0 人在发冷。 新浣熊不会加入，除非你有食物储备和分类良好的垃圾堆。",
    "Lasts forever. Couldn't possibly cause any problems down the line.": "永远持续下去。 不可能导致任何问题。",
    "Metal": "金属",
    "Paper": "纸",
    "Plastic": "塑料",
    "Portable tree essence.": "便携树精。",
    "Raccoons": "浣熊",
    "Time to take out the trash...and place it neatly into discrete piles.": "是时候把垃圾拿出来了……把它整齐地堆成一堆。",
    "Time Until Raccoons Eat": "浣熊吃东西的时间",
    "Wood": "木头",
    "Okey dokey": "好吧，好吧",
    "The human is shocked by your stand": "人类被你的立场震惊了",
    "And you're feeling rude": "你感觉很粗鲁",
    "Another bountiful cache": "另一个丰富的缓存",
    "But you're a clean dude": "但你是个干净的家伙",
    "But you're not in the mood": "但你没心情",
    "Cloud Cleaning": "云清扫",
    "Corn dogs for years": "多年来的玉米狗",
    "He dumps some new trash": "他倒了一些新垃圾",
    "It could be good food": "这可能是很好的食物",
    "Near a carnival dumpster with friends": "和朋友一起在嘉年华垃圾箱附近",
    "Now everyone pokes at the fluff": "现在每个人都在戳绒毛",
    "The feasting seems like it won't end": "盛宴似乎不会结束",
    "Then a worker comes into your sight": "然后一个工人进入你的视线",
    "This sure is mysterious stuff": "这肯定是神秘的东西",
    "This trash is a glorious blend": "这种垃圾是一种光荣的混合",
    "Time Until New Raccoons Arrive": "新浣熊到来的时间",
    "With a new treat that's so pink and light": "有了一种粉红色和轻盈的新款待",
    "Word of your well-sorted trash pile spreads. Your group of raccoons is growing.": "您分类良好的垃圾堆的消息传播开来。 你的浣熊群正在增长。",
    "You eat elephant ears": "你吃大象耳朵",
    "You gobble to show you're so tough": "你狼吞虎咽地表明你很坚强",
    "Your friends make a toast to the night": "你的朋友们为夜晚干杯",
    "Act II": "第二幕",
    "Advanced Stealing": "高级偷窃",
    "Animal Nature": "动物性质",
    "Apparently those noises they make actually mean something? Huh. Go figure.": "显然，他们发出的那些声音实际上意味着什么？嗯。去搞清楚。",
    "Attracts larger crowds of wandering raccoons to join your society.": "吸引更多的流浪浣熊加入你的社会。",
    "Book House": "书屋",
    "Build": "建造",
    "Build Queue": "建造队列",
    "Burying Food": "埋葬食物",
    "Counterfeiting Money": "伪造货币",
    "Detritus Ex Machina": "Detritus Ex Machina",
    "Develop the science of studying humans, the creators of the trash source.": "发展研究人类的科学，人类是垃圾源的创造者。",
    "Earn more resources when sorting trash.": "分类垃圾时赚取更多资源。",
    "Hands full of sweet treats": "满手甜食",
    "Human Language": "人类语言",
    "Human Studies": "人类研究",
    "Humans print this stuff all the time and then they use it to get more stuff. Seems pretty harmless.": "人类一直在打印这些东西，然后他们用它来获取更多的东西。看起来很无害。",
    "Humans spend most of their lives inside of specially constructed boxes. We, too, can dream such dreams.": "人类大部分时间都在特制的盒子里度过。我们也可以做这样的梦。",
    "Increases job efficiency.": "提高工作效率。",
    "Increases trash collection.": "增加垃圾收集。",
    "Label Maker": "标签机",
    "Live in decorative features": "生活在装饰特色",
    "No research in progress": "没有进行中的研究",
    "No research is in progress.": "没有研究正在进行中。",
    "Nothin' in the queue.": "队列中没有任何内容。",
    "Nothin'.": "没什么。",
    "Now you can prove things, even if no one believes you.": "现在你可以证明事情，即使没有人相信你。",
    "One day while out far on a lark": "有一天，远在云雀上",
    "Promise capture won't last": "承诺捕获不会持续",
    "Put some wheels on an old washing machine and just load that sucker up with trash.": "在旧洗衣机上装上一些轮子，然后把垃圾装满那个吸盘。",
    "Raccoon Boxes": "浣熊盒",
    "Requires:": "要求：",
    "Research": "研究",
    "Research Advanced Stealing": "研究高级窃取",
    "Signal ownership over friend and foe alike by sticking labels to them.": "通过给他们贴上标签来表明对朋友和敌人的所有权。",
    "Speeds up building.": "加快建设。",
    "Speeds up trash sorting.": "加快垃圾分类。",
    "Stuff old food in the ground, put some water on it, and even more food comes out. Works with pretty much all food.": "把旧食物塞进地里，在上面放点水，就会有更多的食物出来。适用于几乎所有食物。",
    "The Scientific Method": "科学方法",
    "The stock market is basically just a giant trashcan you can pull value from whenever you want.": "股市基本上只是一个巨大的垃圾桶，你可以随时从中获取价值。",
    "Their caged lives seem rather dark": "他们笼中的生活似乎相当黑暗",
    "They point and laugh, flinging their spit": "他们指指点点大笑，吐唾沫",
    "They taunt the great beasts": "他们嘲弄巨兽",
    "This is like a house for raccoons, except only books live here. This is how a civilized society shows respect for books.": "这就像一个浣熊的房子，除了这里只有书。这就是文明社会对书籍的尊重。",
    "This whole scene has you in a fit": "这整个场景让你合不拢嘴",
    "Time to complete: 0:15": "完成时间：0:15",
    "Time to complete: 0:30": "完成时间：0:30",
    "Trash Carrier": "垃圾车",
    "Try to ask the cat out but fall flat": "试着约猫出去，但结果一落千丈",
    "Unlocks building farms. Farms increase the amount of food gathered.": "解锁建筑农场。农场增加了收集的食物量。",
    "Unlocks building shelters. Each shelter increases the maximum number of raccoons by 20.": "解锁建筑庇护所。每个庇护所都会增加 20 只浣熊的最大数量。",
    "Unlocks the next act.": "解锁下一幕。",
    "Unlocks the rest of the research options.": "解锁其余的研究选项。",
    "Where big, wild creatures": "哪里有大型的野生动物",
    "With a nearby striped, mighty cat": "附近有一只条纹强大的猫",
    "You also see kids, little twits": "你也看到孩子们，小笨蛋",
    "You decide that you'll have a chat": "您决定聊天",
    "You find something particularly special in a recent batch of trash.": "你在最近的一批垃圾中发现了一些特别的东西。",
    "You stumble on a new type of park": "你偶然发现了一种新型公园",
    "You walk up to the glass": "你走到玻璃前",
    "You're a rude bag of gas": "你是一个粗鲁的汽油袋",
    "You're in love, talking fast": "你恋爱了，说话很快",
    "Breaking news! I’ve been studying humans and I’ve noticed that they say things like “Breaking news!” to get attention. That’s just one of the valuable lessons I’ve learned. I think it might be worth setting up a permanent way to research them.": "爆炸新闻！ 我一直在研究人类，我注意到他们会说“突发新闻！”之类的话。 引起注意。 这只是我学到的宝贵经验之一。 我认为建立一种永久的方法来研究它们可能是值得的。",
    "Hey everyone! I know we’ve all recently become aware of ourselves, learned to read and write, and have started constructing rudimentary shelters. It’s a lot. But I wanted to post this up and let everyone know that it’s OK to just chill. Changing your entire conception of self and society is a lot to go through, so it’s totally valid to take some time for yourself.": "嘿大家！ 我知道我们最近都意识到了自己，学会了阅读和写作，并开始建造简陋的避难所。 很多。 但我想把它贴出来，让大家知道放松一下是可以的。 改变你对自我和社会的整个概念需要经历很多事情，所以为自己花点时间是完全有效的。",
    "Completed: Human Studies": "完成：人类研究",
    "Emergency Bulletin": "紧急公告",
    "Human Studies ✔️": "人类研究✔️",
    "Message board unlocked.": "留言板解锁。",
    "There isn't enough trash to sort! Go get some trash first.": "没有足够的垃圾分类！ 先去捡垃圾吧。",
    "We Live in a Society": "我们生活在一个社会中",
    "What comes next may shock you: haha, sorry just practicing.": "接下来的事情可能会让你大吃一惊：哈哈，抱歉刚刚练习。",
    "You now understand the complex cocktail of emotions that these poor, hairless creatures possess.": "你现在明白了这些可怜的、无毛的生物所拥有的复杂的情感混合物。",
    "Exciting New Food from the Ground": "来自地面的令人兴奋的新食物",
    "Farm": "农场",
    "Increases the amount of food gathered.": "增加收集的食物量。",
    "It's upsetting to pull food out of the earth instead of the trash, but we're adjusting.": "将食物而不是垃圾从地球中取出是令人不安的，但我们正在调整。",
    "Looking for someone to trade some sub sandwiches, which are food I can eat, for a large collection of golden dubloons, which are pirate treasure and rather inedible. Thanks for your consideration.": "找人交换一些三明治，这是我可以吃的食物，大量的黄金达布隆，这是海盗宝藏，相当不可食用。 感谢您的考虑。",
    "Not currently building anything.": "目前没有建造任何东西。",
    "Some more raccoons are coming this way! They'll be here in 1 second. Make sure there's enough space available for them to settle in.": "更多的浣熊正朝这边来！ 他们会在 1 秒内到这里。 确保有足够的空间供他们安顿下来。",
    "Subs Not Dubs": "潜艇不是配音",
    "What once was dead lives yet again. Food necromancy rules.": "曾经死去的东西又复活了。 食物死灵法则。",
    "You can now build Farms": "您现在可以建造农场",
    "Building speed is reduced due to a food shortage. Gather more food for your raccoons!": "由于食物短缺，建筑速度降低。 为你的浣熊收集更多食物！",
    "Your raccoons are too hungry to research at a normal speed. Gather more food!": "你的浣熊太饿了，无法以正常速度进行研究。 收集更多食物！",
    "Your raccoons are too hungry to work at a normal speed. Gather more food!": "你的浣熊太饿了，无法以正常速度工作。 收集更多食物！",
    "A bold improvement on what humans call \"cars.\"": "对人类所谓的“汽车”的大胆改进。",
    "Cancel building this farm to refund the purchase cost of  50 bones and 50 cloth.": "取消建造这个农场，返还50块骨头和50块布的购买成本。",
    "Comes with one (1) \"Bless this Mess\" welcome mat.": "随附一 (1) 个“祝福这个混乱”欢迎垫。",
    "Don't let yourself get boxed in by old, detoriating cardboard. Introducing: a box for the modern lifestyle.": "不要让自己被陈旧的、变形的纸板困住。介绍：现代生活方式的盒子。",
    "Give Us Shelter": "给我们庇护",
    "Idea of Man Looking for Idea of Woman": "男人的想法寻找女人的想法",
    "Increases the maximum number of raccoons who can join your crew.": "增加可以加入您的船员的浣熊的最大数量。",
    "It’s like :0 and then it’s like :) hahahahha u know what I mean?!?!": "就像 :0 然后就像 :) haha​​hahha 你知道我的意思吗？！？！",
    "Me, a raccoon in a stunning blonde wig, red dress, and expertly repaired heels.": "我是一只浣熊，戴着漂亮的金色假发，穿着红色连衣裙，脚跟修得精巧。",
    "Meet me under the big branch at the back of the tree. I must perform the awful gender play of the humans. I crave their pain.": "在树后的大树枝下见我。我必须表演人类可怕的性别游戏。我渴望他们的痛苦。",
    "More raccoons will join periodically": "更多浣熊将定期加入",
    "No more pointing at restaurant menus while looking up at the waiter with an expression of polite contrition.": "不再指着餐厅的菜单，同时用礼貌的忏悔表情看着服务员。",
    "Party at Landfill": "垃圾填埋场派对",
    "Shelter": "庇护所",
    "tfw u tip the trash can over": "tfw你把垃圾桶翻过来",
    "Trash collection increased": "垃圾收集增加",
    "You can now build Shelters": "您现在可以建造庇护所",
    "You, a raccoon in a fedora (preferably few holes) and a decent-smelling trench coat. Maybe you found a pipe or a broken toy gun around.": "你，一只戴着软呢帽的浣熊（最好是几个洞）和一件闻起来像样的风衣。也许你在周围发现了一根管子或一把坏掉的玩具枪。",
    "Beakers! Flasks! Burners! Fashion!": "烧杯！烧瓶！燃烧器！时尚！",
    "Building speed increased": "建造速度增加",
    "Easy to make and free of consequence, just like a fire.": "易于制作且没有后果，就像火一样。",
    "Going on vacation to a different tree soon, but I’ve noticed that when I leave a lot of my paper and plastic trash gets blown away. Looking for someone to sit on my trash while I’m gone. You can have some of the trash, but not all of it.": "很快要去另一棵树度假，但我注意到当我留下很多纸和塑料垃圾时，会被吹走。我不在的时候找人坐在我的垃圾桶上。你可以有一些垃圾，但不是全部。",
    "I warned you it was my worst desire!!": "我警告过你这是我最坏的愿望！！",
    "I'm looking for a powerful potion that can help me fulfill my worst desires. What are they, you ask? Oh, you didn't ask? Well...would you like to hear them anyway? Keep reading!": "我正在寻找一种强大的药水，可以帮助我满足我最坏的愿望。你问他们是什么？哦，你没问？嗯……你想听听他们的声音吗？继续阅读！",
    "Jobs now take less time to perform.": "作业现在需要更少的时间来执行。",
    "Lost my hahahaha shut up wallet": "丢了我的哈哈哈哈闭嘴钱包",
    "Me, a person, hahahaha dude STOP was walking around on only two legs. My dumb brain could not keep track of my powerful paper holder, the wallet hahahaha and I lost it.": "我，一个人，哈哈哈哈老兄STOP只用两条腿走来走去。我的愚蠢大脑无法跟踪我强大的纸夹，钱包哈哈哈，我把它弄丢了。",
    "Mmm, yes. Wonderful. Consent is an important part of any interaction. So, what I want is a potion that will help me pop a pimple so hard that I fall over.": "嗯，是的。精彩的。同意是任何互动的重要组成部分。所以，我想要的是一种药水，它可以帮助我把一个疙瘩挤得那么厉害，以至于我摔倒了。",
    "Must have 3-5 years of sitting experience. LARGE BUTTS only. I have been blessed with a lot of trash.": "必须有3-5年的坐姿经验。仅限大屁股。我很幸运有很多垃圾。",
    "Oh my god I can’t do this anymore hahaha holy crap WOW. I know I know it’s too good. Did you get all of that down? Why are you still writing? Ok, just stop and post whatever you’ve got.": "哦，天哪，我不能再这样做了，哈哈哈，天哪，哇。我知道我知道这太好了。你把这一切都记下来了吗？为什么还在写？好吧，停下来张贴你所拥有的一切。",
    "Please find my wallet!! Otherwise I cannot exercise my power as a tall, nearly hairless mammal!": "请找到我的钱包！！否则我无法发挥我作为一个高大、几乎没有毛的哺乳动物的力量！",
    "Powerful Potions": "强力药水",
    "THIS POP-UP IS PROPERTY OF RACCOON. IF FOUND, PLEASE RETURN TO RACCOON.": "这个弹出窗口是 Raccoon 的财产。如果找到，请返回 RACCOON。",
    "Trash Sitters Wanted": "垃圾保姆通缉",
    "Trash sorting yield increased": "垃圾分类收率提高",
    "Yes...come closer to this note, stranger...mmm, perfect.": "是的……靠近这张纸条，陌生人……嗯，完美。",
    "Ah, finally! Nothing to do now but put these cool sunglasses on my face and read these books *drops glasses* oh no": "啊，终于！ 现在无事可做，只好把这些酷酷的太阳镜戴在我脸上读这些书*戴眼镜*哦不",
    "Anyone seen any baby shoes around? I don’t care if they’re used or not, I just love the dang things. Hit me up! - Ernest": "有人看到附近有婴儿鞋吗？ 我不在乎它们是否被使用，我只是喜欢那些该死的东西。 打我！ - 欧内斯特",
    "Baby Shoes": "婴儿鞋",
    "My (3R) partner (3R) and I are looking for trash. Please contact us if you have trash. All trash considered. No non-trash bartering.": "我的 (3R) 伙伴 (3R) 和我正在寻找垃圾。 如果您有垃圾请联系我们。 所有垃圾都考虑在内。 没有非垃圾易货交易。",
    "tl;dr: looking for some trash thanks": "tl;博士：寻找一些垃圾谢谢",
    "Trash sorting efficiency increased": "垃圾分拣效率提高",
    "(new!)": "（新！）",
    "[patting a tree lightly and whispering] This baby can fit so much liquid nitroglycerin in it.": "（轻拍一棵树，低声说）这娃能装这么多液态硝酸甘油。",
    "/unit": "/单位",
    "100 Floor Dungeons: Should they stay in video games or are they perfect for your new summer home?": "100 层地下城：它们应该留在电子游戏中还是非常适合您的新避暑别墅？",
    "A filling side dish that's sure to thrill at any power plant potluck.": "一种填充配菜，肯定会在任何发电厂的便餐中令人兴奋。",
    "A state made of pure sunshine that seems to drive anyone inside it to live with a furious energy.": "一种由纯粹的阳光构成的状态，似乎驱使其中的任何人以狂暴的能量生活。",
    "Ability: Bear Down": "能力：压倒",
    "Ability: Binsider Trading": "能力：垃圾箱 交易",
    "Ability: Let's Get Frackin'": "能力：让我们开始吧",
    "Ability: Roll the Bones": "技能：抽取骨头",
    "Act III": "第三幕",
    "After you've bent the market to your will, gambling is one of the only ways to get the legitimate thrill of risk.": "在你让市场服从你的意愿之后，赌博是获得合法风险快感的唯一方法之一。",
    "Ah yes, the big sleep. The most powerful nap ever invented.": "啊，是的，大睡。有史以来最强大的午睡。",
    "All the world's a game,": "全世界都是游戏，",
    "An endless system of debt, much like a hamster wheel, is the best way to power an economy.": "无休止的债务系统，就像仓鼠轮子一样，是推动经济发展的最佳方式。",
    "And all the creatures in it merely gamers.": "而其中的所有生物都只是游戏玩家。",
    "and i'll hit you with arrows of wisdom from my mighty business bow": "我会用我强大的商业弓箭射中你",
    "and i'm the mayor": "我是市长",
    "and ready to dominate the competition?": "并准备好称霸竞争？",
    "and they won't stop their markets because they love money too much": "他们不会因为太爱钱而停止市场",
    "Another record quarter for jobs growth. \"Everyone has a job,\" the Job Minister said in a report. \"All jobs are objectively good.\"": "就业增长又一个创纪录的季度。 “每个人都有一份工作，”就业部长在一份报告中说。 “所有工作客观上都是好的。”",
    "are any classes at your school open?": "你们学校有课吗？",
    "are you really a baby or an adult": "你真的是婴儿还是成年人",
    "baby?": "婴儿？",
    "basically just make a lot of money": "基本上只是赚很多钱",
    "be aggressive with it": "积极进取",
    "Beans:": "豆子：",
    "Bear Down": "忍了下来",
    "Bear Down [E]": "熊熊[E]",
    "because i'm all about the money": "因为我只关心钱",
    "Binsider Trading": "垃圾箱 交易",
    "Binsider Trading [Q]": "垃圾箱 交易 [Q]",
    "Bone Clones": "骨头克隆",
    "BREAKING: I'm one step closer to the edge and I'm about to": "BREAKING：我离边缘更近了一步，我即将",
    "Broil the Earth": "烤地球",
    "Burn ban reminder: it's currently illegal not to have a barrel full of fire in front of your home at all times. Best to have a couple in case one goes out.": "禁火令提醒：目前在家门前不能一直装满火的桶是违法的。最好有一对，以防万一出去。",
    "Business Beans": "商业豆",
    "Business Botany": "商业植物学",
    "but I'm feeling a little lost": "但我有点失落",
    "Buy": "购买",
    "Buy 1 Culture Share": "购买 1 份文化股份",
    "Buy 1 Death Share": "购买 1 份死亡股份",
    "Buy 1 Finance Share": "购买 1 份金融股份",
    "Buy 1 Natural Resources Share": "购买 1 份自然资源股份",
    "Buy Low": "低价买入",
    "buy shares with the money you make from selling trash!": "用卖垃圾赚的钱买股票！",
    "by playing with the stonk market": "通过玩 stonk 市场",
    "by which i mean just ask me all your questions": "我的意思是问我你所有的问题",
    "Cash Raccoons Everywhere Around Me": "我周围到处都是现金浣熊",
    "clearly this is an emergency and i'm bored so...": "显然这是紧急情况，我很无聊，所以...",
    "click the button on your phone that looks like a jagged line to track the price": "单击手机上看起来像锯齿状线的按钮以跟踪价格",
    "Clone your rolled dice so you roll twice every time, either doubling your success or failure.": "克隆你掷出的骰子，这样你每次掷骰子两次，成功或失败翻倍。",
    "Coal 'n Cleanse": "煤清洁",
    "Coal Slaw": "煤条",
    "Conversations": "对话",
    "cool...": "酷...",
    "Cruder Oil": "原油",
    "Crypt Currency": "加密货币",
    "Culture": "文化",
    "Death": "死亡",
    "Debt for Teens": "青少年债务",
    "Debtor's Vision": "债务人的愿景",
    "Dice for those who like their cheating with a certain heft.": "为那些喜欢作弊的人掷骰子。",
    "do you have any tips for buying and selling shares?": "你有什么买卖股票的技巧吗？",
    "Do your part to power the trash economy! Throw out all your old stuff and buy slightly better stuff.": "尽自己的一份力量来推动垃圾经济！扔掉你所有的旧东西，买稍微好一点的东西。",
    "Don't be a toxic waster! Dump any harmful chemicals directly into the nearest large body of water.": "不要成为有毒废物！将任何有害化学物质直接倾倒到最近的大型水体中。",
    "don't stress if you lose it all": "如果你失去了一切不要紧张",
    "Double or Something": "双打什么的",
    "Down": "下",
    "Drop price": "降价",
    "Economic inequality: Is there a real cause to pout or is this just another case of the Mondays?": "经济不平等：是否有真正的撅嘴的原因，或者这只是星期一的另一种情况？",
    "elephant operator?": "大象操作员？",
    "Emergency alert: RaccoonBots recalled due to extremely high murder rate. RaccoonBot Inc. is \"working on a fix\".": "紧急警报：RaccoonBots 因谋杀率极高而被召回。 RaccoonBot Inc. 正在“解决问题”。",
    "Even more humans died today from complications related to raccoons taking over the planet. Our thoughts and prayers are with the human race.": "今天，更多的人死于与浣熊占领地球有关的并发症。我们的思想和祈祷与人类同在。",
    "Every week on Tuesday we announce we're out of trash, then we \"find more in the back room\" on Thursday.": "每周二我们宣布我们没有垃圾了，然后我们在周四“在后面的房间里找到更多”。",
    "exactly!!!": "确切地！！！",
    "Exploding Trees": "爆炸树",
    "False Scarcity": "虚假的稀缺",
    "Farting: Public nuisance, personal expression, or just another mechanism of control for Big Bean?": "放屁：公害、个人表达，还是 Big Bean 的另一种控制机制？",
    "Finance": "金融",
    "Fiveclosure": "五关",
    "Florida": "佛罗里达",
    "Folded-Up Coaster": "折叠杯垫",
    "from": "从",
    "Full of the complex blend of vitamins and minerals that every budding capital enterprise needs.": "充满了每个新兴资本企业所需的维生素和矿物质的复杂混合物。",
    "Generate 2x more trash for ten seconds.": "在 10 秒内产生 2 倍以上的垃圾。",
    "Global Business Level": "全局业务等级",
    "good to know! how do I sell instead of buying?": "很高兴知道！我如何出售而不是购买？",
    "got it — thanks!": "知道了谢谢！",
    "Gotta Go Fast Fashion": "必须走快时尚",
    "great so let's start with that first one": "太好了，让我们从第一个开始",
    "Grinding: Out of the club and onto the world map to get that sweet, sweet EXP": "磨练：走出俱乐部，进入世界地图，获得甜蜜的经验",
    "have a blast out there buddy": "在那里玩得开心，伙计",
    "hello": "你好",
    "here's my card": "这是我的名片",
    "heyyyy baby!": "嘿嘿宝贝！",
    "Hoss-style Takeover": "霍斯式收购",
    "how do i get games on this phone": "这个手机怎么玩游戏",
    "how do i make the most out of business botany and beans?": "我如何充分利用商业植物学和豆类？",
    "how does buying and selling trash work?": "买卖垃圾如何运作？",
    "I also just saw Austin Powers for the first time.": "我也是第一次看到 Austin Powers。",
    "i can easily get you into money baby academy, my lucrative new business school": "我可以很容易地让你进入金钱宝贝学院，我利润丰厚的新商学院",
    "i can make it back in a day by tricking one of the human empires into starting another war": "我可以通过欺骗一个人类帝国开始另一场战争来在一天之内回来",
    "I hope they let us ring the bell on the big screen.": "我希望他们让我们在大屏幕上敲钟。",
    "i should probably start small though": "我可能应该从小处着手",
    "i want to make...": "我要实现...",
    "i'm an adult raccoon": "我是成年浣熊",
    "i'm ready to make mega millions!!!": "我准备好赚百万了！！！",
    "i’ll check in later and introduce you to the gang.": "我稍后会检查并向您介绍该帮派。",
    "I’m advising you to make as much money as possible! And I’m gonna help! We’re gonna take over the world!": "我建议你尽可能多地赚钱！我会帮忙的！我们要接管世界！",
    "I’m an adult. I just love money, baby.": "我是一个成年人。我就是爱钱，宝贝。",
    "Iceberg Cubes": "冰山立方体",
    "if you buy 10 of any share, you level up and get a business bean.": "如果您购买 10 份任何股份，您将升级并获得一个商业 bean。",
    "if you buy enough shares in one industry, you'll level up and get a business bean that can make your abilities more powerful": "如果你在一个行业购买了足够多的股票，你就会升级并获得一个可以让你的能力更强大的商业豆",
    "if you get confused about anything just text me": "如果您对任何事情感到困惑，请给我发短信",
    "If you're old enough to be tried as an adult, you're old enough for this 41% APR.": "如果您的年龄足以作为成年人接受审判，那么您的年龄足以承受这 41% 的年利率。",
    "Incoming chat": "传入聊天",
    "Increases the trash production bonus you get while Let's Get Frackin' is active by how much trash you have.": "在 让我们开始吧 处于活动状态时，根据您拥有的垃圾数量增加您获得的垃圾生产奖励。",
    "Industrial Waste": "工业废料",
    "Investments": "投资",
    "is there anything else?": "还有别的事吗？",
    "isn't that dope?": "那不是麻醉剂吗？",
    "it goes up and down based on whatever humans pretend it's worth.": "它会根据人类假装它的价值而上下波动。",
    "it's a moba basically": "基本上是moba",
    "it's a term i'm trying to make happen": "这是我试图实现的一个术语",
    "it's all made up! so cool!": "都编好了！非常酷！",
    "It's power on paper. Each dollar is equal to a single unit of happiness.": "这是纸上的力量。每美元等于一个幸福单位。",
    "it’s neat sure": "肯定很整洁",
    "jk on that last one.": "jk 在最后一个。",
    "keep on being the best mayor out there": "继续做最好的市长",
    "keep your eye on the total sale price by the sell button and how the price of trash is going up and down in your phone’s stonks app.": "通过出售按钮密切关注总销售价格，以及手机的 stonks 应用程序中垃圾价格的涨跌情况。",
    "kinda busy right now champ": "有点忙现在冠军",
    "Let's Get Frackin'": "让我们开始吧",
    "Let's Get Frackin' [R]": "让我们开始吧 [R]",
    "Let's Get Frackin' generates 50% more trash and does so in an immediate lump sum.": "让我们开始吧 产生的垃圾增加了 50%，而且一次性一次性完成。",
    "LFT": "LFT",
    "like a simulation": "像模拟一样",
    "like the tea with bubbles?": "喜欢有气泡的茶吗？",
    "lmao my phone's predictive text typed that": "lmao 我手机的预测文本输入了",
    "lmao you’ll get it as you try things out! just trust me buddy!": "lmao 你会在你尝试的时候得到它！相信我，伙计！",
    "lol i'll be your financial advisor basically": "哈哈，我基本上是你的财务顾问",
    "lol that's so boring": "哈哈，太无聊了",
    "Long ago someone gave money a fancier name to make the people who have more of it seem smarter.": "很久以前，有人给钱起了一个更漂亮的名字，让拥有更多钱的人看起来更聪明。",
    "love that stuff": "喜欢那些东西",
    "Lowers the trash production bonus you get while Let's Get Frackin' is active, but the ability lasts much longer.": "降低在 让我们开始吧 激活时获得的垃圾生产加成，但该能力持续时间更长。",
    "Luxury Pogs": "豪华猪",
    "Lv.": "等级",
    "make US lots of money! sorry autocorrect...": "让美国大赚一笔！抱歉自动更正...",
    "make us more real money": "让我们赚更多的钱",
    "Manually choose whether to raise or lower all share prices by a small amount.": "手动选择是小幅提高还是降低所有股价。",
    "Manually choose which share price(s) will drop.": "手动选择将下跌的股价。",
    "Market never crashes.": "市场永远不会崩溃。",
    "Market temporarily freezes at the increased price before crashing.": "市场在崩盘前暂时冻结在上涨的价格上。",
    "Massive father/son crowds head into the city to welcome the black parade": "大批父子涌入城市迎接黑人游行",
    "Medicated Bonds": "药物债券",
    "Money": "钱",
    "Money Baby": "钱宝贝",
    "Money Baby Academy": "金钱宝贝学院",
    "Money Baby Academy is now in session!": "金钱宝贝学院 开课啦！",
    "My accountant told me if you hide your best trash under a shell, you don't have to pay taxes on it.": "我的会计师告诉我，如果你把最好的垃圾藏在一个壳下，你就不必为此纳税。",
    "my name is TK": "我叫TK",
    "nah you're good champ": "不，你是个好冠军",
    "Natural Resources": "自然资源",
    "New message from": "来自的新消息",
    "no a Manipulated Online Banking Adventure": "没有被操纵的网上银行冒险",
    "no i mean like lost making money": "不，我的意思是像失去赚钱一样",
    "no it's real": "不，这是真的",
    "no prob i'm always happy to help make a wealthy raccoon even richer": "没问题，我总是很乐意帮助一只富有的浣熊变得更富有",
    "Not a big deal. Just a bunch of shadows on the wall of a cave or whatever.": "没有大碍。只是洞穴墙壁上的一堆阴影或其他任何东西。",
    "Not only are we using billions of gallons of water, we're also ruining the soil, air, and water nearby. Now that's efficiency!": "我们不仅使用了数十亿加仑的水，还破坏了附近的土壤、空气和水。这就是效率！",
    "nothing i guess": "我猜什么都没有",
    "Officials were shocked and pleased yesterday when several enormous garbage islands merged and conveniently created the first bridge across the Pacific Ocean": "昨天，当几个巨大的垃圾岛合并并方便地建造了横跨太平洋的第一座桥时，官员们感到震惊和高兴",
    "oh my bad": "哦，我的坏",
    "oh you’re gone now ok": "哦，你现在走了，好吧",
    "ok": "好的",
    "ok great": "好，很好",
    "ok i lied about being busy!": "好吧，我谎称自己很忙！",
    "ok i teach using the socratic method": "好的，我用苏格拉底式教学",
    "ok so what am i doing?": "好的，我在做什么？",
    "ok sure i'll give it a shot": "好的，我会试一试",
    "ok what are you advising me to do exactly": "好的，你建议我做什么",
    "Ok you’re in charge! have fun dominating and making bank!": "好吧，你负责！玩得开心主宰银行！",
    "Okey doke": "好吧好吧",
    "Own the Entire Means of Production": "拥有全部生产资料",
    "please don't hurt me": "请不要伤害我",
    "Popular fur cream discontinued after consumers discovered ties to the controversial bones industry": "在消费者发现与有争议的骨头行业有联系后，流行的皮草霜停产",
    "Popular RaccoonTube sensation Trashy Tim dead at age 5 after imbibing a whole barge of trash on a livestream": "流行的 RaccoonTube 轰动Trashy Tim 在直播中吸了一整艘垃圾后在 5 岁时死亡",
    "pretty sure you have a maps app": "很确定你有一个地图应用程序",
    "Price control:": "价格控制：",
    "Produce twice as much trash while Let's Get Frackin' is active.": "当 让我们开始吧 处于活动状态时，产生两倍的垃圾。",
    "RaccoonBot explodes in popularity after CEO promises that explosions are under control": "在 CEO 承诺爆炸事件得到控制后，RaccoonBot 大受欢迎",
    "Raccoons in the swamp community reverse their position, now welcoming people into their swamp": "沼泽社区中的浣熊改变了他们的立场，现在欢迎人们进入他们的沼泽",
    "Raise your Global Business Level to 40": "将您的全局业务级别提高到 40",
    "Rapidly increase trash prices but market volatility increases.": "垃圾价格快速上涨，但市场波动加剧。",
    "Ready": "已就绪",
    "Recover from trash market crashes faster.": "更快地从垃圾市场崩溃中恢复过来。",
    "Researchers in Transylvania hold conference today to announce that the world is a vampire": "特兰西瓦尼亚的研究人员今天召开会议宣布世界是一个吸血鬼",
    "Right in the feelers: a new type of pollution is destroying antennae across the animal kingdom": "触手可及：一种新型污染正在摧毁整个动物王国的触角",
    "Ring That Bell": "敲响那钟",
    "Roll for a 50% chance to double your money or cut it in half.": "抽取有 50% 的机会使您的钱翻倍或减半。",
    "Roll the Bones": "抽取骨头",
    "Roll the Bones [W]": "抽取骨头 [W]",
    "Rolling...": "抽取中...",
    "Rome before the fall: get discounted tickets to visit Italy's famous capital this summer": "秋季前的罗马：今夏畅游意大利著名首都打折机票",
    "Roughly doubles the duration of Binsider Trading.": "垃圾箱交易 的持续时间大约翻倍。",
    "Sale price:": "销售价格：",
    "Sell": "出售",
    "Sell High": "高价出售",
    "Sell!": "出售！",
    "share": "股份",
    "Share price drops are larger but increases are smaller.": "股价跌幅较大，但涨幅较小。",
    "Share price increases are larger but drops are smaller.": "股价涨幅较大，但跌幅较小。",
    "Shares take 30 seconds to return to normal prices.": "股价需要 30 秒才能恢复到正常价格。",
    "Shell Company": "壳牌公司",
    "Sit back and relax with a drink cooled by fresh ice we chipped off melting icebergs in Antarctica.": "坐下来放松一下，喝一杯我们在南极洲融化的冰山上切下的新鲜冰块冷却的饮料。",
    "SLAMMIN' back into the marketplace at an even higher price!": "SLAMMIN' 以更高的价格重返市场！",
    "Slow-cook the Globe": "慢煮地球",
    "so are you like": "你也喜欢吗",
    "So clean you'll swear it's safe to burn.": "如此干净，你会发誓燃烧它是安全的。",
    "so it's all a beautiful, natural system of profit": "所以这都是一个美丽的、自然的利润系统",
    "sorry i'm the CEO": "对不起，我是 CEO",
    "sorry teaching makes me a lil aggro": "对不起教学让我成为一个小仇恨",
    "sorry to bother you MB": "很抱歉打扰你MB",
    "sounds fun!": "听起来很有趣！",
    "Special Report: What's that stink and where is it coming from?": "特别报道：那是什么臭味，又是从哪里来的？",
    "Stay tuned after the weather for a special report on The Remainder, a trashy new religion that is sweeping the globe": "天气后请继续关注关于 The Remainder 的特别报道，这是一种正在席卷全局的垃圾新宗教",
    "Stonks are way up, baby! Oh yeah! Groovy!": "斯托克斯正在上升，宝贝！哦耶！时髦！",
    "Subject:": "主题：",
    "Sure Bets": "肯定的赌注",
    "thanks! I think I'm good for now.": "谢谢！我想我现在很好。",
    "that's a power move. you might want to write that down.": "这是一个权力举动。你可能想把它写下来。",
    "The brand-new RaccoonBot can be a friend, a lover, and an assistant—with no ethical concerns whatsoever": "全新的 RaccoonBot 可以成为朋友、爱人和助手——没有任何道德问题",
    "The economy is waaaaaay UP! Like a rollercoaster! Weeeeeeeee!!!!": "经济是waaaaaay UP！像过山车一样！呜呜呜！！！",
    "The Folders": "文件夹",
    "The Holders": "持有人",
    "The invisible hand was too subtle for the amount of market control we wanted.": "看不见的手对于我们想要的市场控制量来说太微妙了。",
    "the more shares you have in an industry, the more of that industry's trash you get": "你在一个行业中的份额越多，你得到的那个行业的垃圾就越多",
    "The next logical step after how profitable foreclosures have been.": "在止赎是多么有利可图之后的下一个合乎逻辑的步骤。",
    "The odds of double or nothing were too unattractive.": "双倍或一无所有的可能性太没有吸引力了。",
    "The price of one random share falls while the other share prices rise. These new prices last for 15 seconds.": "一只随机股票的价格下跌，而另一只股票的价格上涨。这些新价格持续 15 秒。",
    "the stonk market is just like a fun video game that wealthy people play. you're gonna love it!!": "stonk 市场就像有钱人玩的有趣的电子游戏。你会喜欢的！！",
    "the syllabus for MBA is: make money, then party hardy": "MBA的教学大纲是：赚钱，然后聚会",
    "These clothes come in a disposable bag so you can conveniently throw them away after a single use.": "这些衣服装在一次性袋子里，因此您可以在一次使用后方便地扔掉它们。",
    "These were already here when we arrived so presumably they'll last forever.": "我们到达时它们已经在这里了，所以大概它们会永远存在。",
    "they call me money baby": "他们叫我钱宝贝",
    "This oil cusses.": "这油诅咒。",
    "Too cute: Local raccoon trapped by a pile of cuddly, stuffed bears": "太可爱了：被一堆可爱的毛绒熊困住的当地浣熊",
    "totally psyched": "完全精神错乱",
    "Trash Marketplace": "垃圾市场",
    "Trash Money Millionaires": "垃圾钱百万富翁",
    "Trash owned:": "拥有的垃圾：",
    "Trash price doubles every 30 seconds even when Binsider Trading isn't active.": "即使 垃圾箱 未激活，垃圾价格每 30 秒翻一番。",
    "Trash prices increase by an additional 50% when Binsider Trading is active.": "当 垃圾箱 激活时，垃圾价格额外增加 50%。",
    "Trash production hit record highs today. Raccoon officials are expected to celebrate by assembling the materials for a lavish party and then throwing them away.": "今天的垃圾产量创下历史新高。浣熊官员将通过为一个奢华的派对组装材料然后扔掉来庆祝。",
    "Triple Bypass": "三重旁路",
    "Triple your money on a successful roll.": "成功抽取您的资金三倍。",
    "try to wait until the amount of trash and the price are as high as possible.": "尽量等到垃圾的数量和价格尽可能高。",
    "tuition is waived because you're going to make me lots of money": "学费被免除，因为你会让我赚很多钱",
    "Two shares drop in price while two rise.": "两只股票下跌，两只股票上涨。",
    "uhhh could you go over the basics with me?": "呃，你能和我一起复习一下基础知识吗？",
    "unless...": "除非...",
    "Up": "向上",
    "Up Next: Chef Richard Raccoon will show us how to flambé a tennis ball": "下一个：厨师理查德浣熊将向我们展示如何燃烧网球",
    "Update: Raccoon PD says virus outbreak was a hoax": "更新：浣熊警察局说病毒爆发是一场骗局",
    "Upgrades can't be changed or purchased when that ability is active.": "当该能力激活时，不能更改或购买升级。",
    "use the button above the shares to toggle buying and selling": "使用股票上方的按钮来切换买卖",
    "use your powerful business abilities to mess with trash generation, trash and share price, or even just gamble if you need to let off some steam": "利用您强大的业务能力来处理垃圾生成、垃圾和股价，或者如果您需要发泄一下，甚至只是赌博",
    "Visible Hand": "看得见的手",
    "Wager Multiplier": "投注乘数",
    "Wager on whether your dice roll will succeed or fail. Bet on yourself for even more profits or bet against yourself to ease your loss.": "赌你的骰子是成功还是失败。对自己下注以获得更多利润，或对自己下注以减轻损失。",
    "Waste: the final frontier.": "废物：最后的边界。",
    "We covered all of the bonds in a doctor-approved financial powder that’s guaranteed to help lower market prices.": "我们用医生批准的金融粉末覆盖了所有债券，保证有助于降低市场价格。",
    "We made a big computer out of bones that does forbidden, skeletal math.": "我们用骨骼制作了一台大型计算机，可以进行禁止的骨骼数学。",
    "We noticed that the market had a wobbly leg, so we folded up a cardboard coaster and stuck it under there.": "我们注意到市场有一条摇摇晃晃的腿，所以我们折叠了一个纸板杯垫，把它贴在下面。",
    "We now ring the big bell several times an hour, which really charges up the market.": "我们现在每小时敲响几次大钟，这确实使市场充满活力。",
    "We send a bunch of caffeinated raccoons to the cable news finance shows where they yell about trash until everyone thinks it's more valuable.": "我们将一堆含咖啡因的浣熊送到有线电视新闻财经节目中，在那里他们大喊垃圾，直到每个人都认为它更有价值。",
    "we're going to set up a dialogue here": "我们要在这里建立一个对话",
    "We're now bypassing three times the amount of regulations!": "我们现在绕过了三倍的规定！",
    "We're still forcibly taking over companies, but we call everyone \"hoss\" like we're cowboys.": "我们仍在强行接管公司，但我们称每个人为“豪斯”，就像我们是牛仔一样。",
    "We're still working on clones with skin, muscles, or organs.": "我们仍在研究具有皮肤、肌肉或器官的克隆体。",
    "Weighted Dice": "加权骰子",
    "Welcome to the big leagues": "欢迎来到大联盟",
    "well we already control a lot of capital": "好吧，我们已经控制了很多资本",
    "what if the humans get mad at us though?": "如果人类生我们的气怎么办？",
    "what should i do with bear down?": "我该怎么办？",
    "what should my overall strategy be?": "我的总体策略应该是什么？",
    "what's cool about rolling the bones?": "抽取骨头有什么好处？",
    "what's the deal with binsider trading?": "垃圾箱 交易是怎么回事？",
    "what's up?": "这是怎么回事？",
    "whats up?": "这是怎么回事？",
    "when should i do fracking?": "我应该什么时候做水力压裂？",
    "who are you?": "你是谁？",
    "who?": "谁？",
    "Wild Cards": "外卡",
    "wow thanks!": "哇谢谢！",
    "y'know mega millions i guess": "我猜你知道百万",
    "yeah i'm sending you 1 million dollars to start": "是的，我给你 1 million 开始",
    "you can also buy and sell shares!": "您还可以买卖股票！",
    "you can also sell shares if you need some quick cash": "如果您需要一些快速现金，您也可以出售股票",
    "You can choose to wager above the amount of money you have and risk going into debt.": "您可以选择在您拥有的金额之上下注，并冒着负债的风险。",
    "you can make money by buying and selling trash": "你可以通过买卖垃圾来赚钱",
    "You don't need a bear for this process, but having one keeps meetings moving at a lively pace.": "这个过程你不需要一只熊，但有一只熊可以让会议以活泼的节奏进行。",
    "You passively generate 25% more trash at all times.": "您始终被动地产生 25% 以上的垃圾。",
    "you save up as much trash as you like and then you sell it!": "您可以随心所欲地收集垃圾，然后将其出售！",
    "You Win!": "你赢了！",
    "Your Global Business Level (GBL) is the sum of all your investment levels combined. Once you hit the level cap you'll gain access to endgame content such as multiple homes and delusions of grandeur.": "您的全局业务等级 (GBL) 是您所有投资等级的总和。达到等级上限后，您将可以访问残局内容，例如多个房屋和宏伟的幻想。",
    "Your total trash doubles every time Let's Get Frackin' activates.": "每次 让我们开始吧 激活时，您的垃圾总量都会翻倍。",
    "yummy": "好吃",
    "/sec": "/秒",
    "% market share)": "％ 市场份额）",
    "All hail": "所有的冰雹",
    "All-time high:": "历史最高点：",
    "All-time low:": "历来最低点：",
    "and": "和",
    "basically 0": "基本为 0",
    "Current Trash Price:": "当前垃圾价格：",
    "Mayor TK": "TK市长",
    "Means of Production Owned:": "拥有的生产资料：",
    "Recent high:": "近期高点：",
    "Recent low:": "近期低点：",
    "Resource Accumulation Bonuses": "资源积累奖励",
    "shares": "股份",
    "Status": "状态",
    "Stonks": "Stonks",
    "the Cotton Candy Chomper": "棉花糖切碎器",
    "the Scampering Scoundrel": "逃跑的恶棍",
    "the Smoothest of Operators": "最流畅的运算符",
    "Trash Generation:": "垃圾生成：",
    "TRASH PRICES": "垃圾价格",
    "...freaks?": "……怪胎？",
    "*perfectly dunks a basketball without sweating* anyway i'm your education advisor or whatever": "*完美地扣篮而不会流汗*无论如何我是你的教育顾问或其他什么",
    "*revs my chopper so loud* haha i can’t hear you but let’s have some fun": "*把我的菜刀开得太响*哈哈，我听不见你的声音，但让我们玩得开心",
    "*shaking my head knowingly while running my fingers through my dangerous hair* if you have to ask you ain't cool enough to know": "*在我的手指穿过我危险的头发时故意摇头*如果你不得不问你不够酷知道",
    "*swoon* sugoi! Wow haha, you're so cool.": "*晕倒* sugoi！哇哈哈，你太酷了。",
    "absolutely not with this sire and liege stuff": "绝对不适合这种陛下和领主的东西",
    "allow me to sit on your trash pile my liege": "让我坐在你的垃圾堆上 我的君主",
    "Also, long may you reign, many good tidings, etc.": "此外，愿你统治长久，许多好消息，等等。",
    "And Basketball Sparklers.": "和篮球火花。",
    "and how did you become a doctor": "你是如何成为一名医生的",
    "and if you lose money just play the market and make more nbd": "如果你赔钱，就玩市场，赚更多的nbd",
    "And Maybe I'm Sexy But I'm Eight Thousand Years Old and My Brain Fell Out.": "也许我很性感，但我已经八千年了，而且我的大脑都掉了。",
    "And Sailor Don't Sink Her: Trapezoid Transformation Era.": "和水手不要沉没她：梯形转型时代。",
    "And Who Left My Garden Hose In Another Dimension?": "谁把我的花园软管留在了另一个维度？",
    "Consider this an official notice that I am ignoring you. I am rubber and you are glue.": "认为这是我无视你的正式通知。我是橡胶，你是胶水。",
    "Cool Teacher": "酷老师",
    "cool's my name and teachin's the game": "酷是我的名字，教学是游戏",
    "Dirt": "污垢",
    "Doc": "文档",
    "everyone please stay on budget": "请大家保持预算",
    "everyone?": "每个人？",
    "fine...": "美好的...",
    "For example recently I've been watching a lot of Sugar Night Surprise Squad.": "例如最近我一直在看很多 Sugar Night Surprise Squad。",
    "Group Session": "小组会议",
    "haha this rules": "哈哈这个规定",
    "haha yes indeed": "哈哈是的",
    "heh heh": "嘿嘿",
    "hello sire": "陛下您好",
    "hi again": "你好，我们又见面了",
    "Hi, I'm Vanilla. Konnichiwa!": "大家好，我是香草。近千华！",
    "Holllllaaaaaaaa": "霍拉拉啊啊啊",
    "how many of there are you": "你有几个",
    "I am Dr. Raccoon.": "我是浣熊博士。",
    "I am your advisor on all medical matters.": "我是您所有医疗事务的顾问。",
    "I did not mean to send the frown.": "我不是故意皱眉的。",
    "I just like a lot of human media from Japan, so sometimes I speak in Japanese and don’t even realize.": "我只是喜欢日本的很多人类媒体，所以有时我用日语说话，甚至没有意识到。",
    "I went to both a medical school and a finishing school, which others in this chat could've sorely used.": "我去了一所医学院和一所完成学校，本次聊天中的其他人可能会非常使用。",
    "i will manage and love the trash in your honor": "我会以你的名义管理和爱垃圾",
    "i'm cool teacher": "我是酷老师",
    "I'm the pop culture advisor. Hajimemashite!": "我是流行文化顾问。 Hajimemashite！",
    "im dirt the garbage advisor": "我弄脏了垃圾顾问",
    "introduce yourselves, ya freaks!": "自我介绍，你们这些怪胎！",
    "is that everyone?": "是每个人吗？",
    "it's cool. we'll use the money on stuff that makes more trash.": "这很酷。我们会把钱用在制造更多垃圾的东西上。",
    "just call me TK": "请叫我TK",
    "just made a cool bil selling some trash": "刚做了一个很酷的 bil 卖一些垃圾",
    "lmao chill out doctor butthead": "lmao 冷静 医生 butthead",
    "no my trash!!": "没有我的垃圾！！",
    "No, there is not. I have tried many times to escape these superfluous group texts.": "不，那里没有。我已经尝试过很多次来逃避这些多余的群文。",
    "not totally familiar with all the words you're using": "不完全熟悉您使用的所有单词",
    "Oh haha, sorry. I didn't even notice.": "哦哈哈，对不起。我什至没有注意到。",
    "Oh my word, the local reprobate is here too. I was not informed about this.": "哦，我的话，当地的谴责也在这里。我没有被告知这件事。",
    "oh neat! so what do I do with the beans?": "哦整洁！那么我该怎么处理这些豆子呢？",
    "ok here we go": "好的，我们开始",
    "ok we're all here!": "好的，我们都在这里！",
    "ok who is this and how did you get in here?": "好的，这是谁，你是怎么进来的？",
    "once you have some beans, open the business botany panel and spend them!": "一旦你有一些豆子，打开商业植物面板并花掉它们！",
    "or is that your name?": "还是那是你的名字？",
    "phew ok": "好的",
    "Please consult me before making any medical rulings! I am an expert.": "在做出任何医疗裁决之前请咨询我！我是专家。",
    "Sell 1 Culture Share": "出售 1 个文化份额",
    "Sell 1 Death Share": "卖出 1 份死亡份额",
    "Sell 1 Finance Share": "卖出 1 股金融股",
    "sire i politely refuse my liege": "陛下，我礼貌地拒绝了我的领主",
    "so i finally figured out how to get everyone in one message:": "所以我终于想出了如何让每个人都收到一条消息：",
    "sup": "支持",
    "there are lots of fun options to make us even wealthier": "有很多有趣的选择可以让我们变得更加富有",
    "there's no way to mute or disable this conversation huh?": "没有办法静音或禁用此对话吧？",
    "there's really no downside to powering up with beans!": "用豆子加电真的没有缺点！",
    "this is a group chat with your advisors": "这是与您的顾问的群聊",
    "this is a lot to process, but thanks for your help i guess": "这需要处理很多，但我想感谢您的帮助",
    "trash trash trash trash trash TRASH TRASH TRASH TRASH TRASH TRASH": "垃圾 垃圾 垃圾 垃圾 垃圾 垃圾 垃圾 垃圾 垃圾 垃圾 垃圾 垃圾",
    "try to invest in whatever sounds fun to you": "尝试投资任何你觉得有趣的东西",
    "Vanilla": "香草",
    "wait are you... a cool teacher?": "等等，你是……一个很酷的老师吗？",
    "we also got rid of all the dumb regulations so you can switch things around whenever": "我们还摆脱了所有愚蠢的规定，因此您可以随时切换",
    "what is that text between asterisks?": "星号之间的文字是什么？",
    "what's good buddy? *cracks a cold one and puts on some shades*": "什么是好伙伴？ *破解一个冷的并戴上一些阴影*",
    "what's NOT cool about gambling?!?": "赌博有什么不酷的？！？",
    "what’s up?": "这是怎么回事？",
    "you can find some truly unfair combos if you play around": "如果你玩，你会发现一些真正不公平的组合",
    "you can take a risk and make way more money": "你可以冒险并赚更多的钱",
    "you get a bean every time you buy enough shares in an industry to level it up": "每次你在一个行业购买足够多的股票来升级它，你就会得到一颗豆子",
    "You should come over for the anime night I host! You’d be the... first guest, haha.": "你应该过来参加我主持的动漫之夜！你会是……第一位客人，哈哈。",
    "yup": "对",
    "and the best part is that none of the studies we've paid for shows that fracking does any harm": "最好的部分是我们支付的所有研究都没有表明水力压裂会造成任何伤害",
    "binsider trading rules!!": "垃圾箱 交易规则！！",
    "but you've gotta sell before it crashes": "但你必须在它崩溃之前卖掉",
    "crank your trash amount and then crank that trash price": "提高你的垃圾量，然后提高垃圾价格",
    "do it all over again! or do it all at once!!": "再做一遍！或一次完成！",
    "it just makes tons of trash and trash is always good": "它只会制造大量垃圾，而垃圾总是好的",
    "it's like playing a game of finance chicken": "就像玩金融鸡游戏",
    "it's pure profit! and it's not illegal because we paid to change all the dumb laws! party time!": "这是纯利润！这并不违法，因为我们花钱改变了所有愚蠢的法律！晚会时间！",
    "lose yourself in the delirious flood of profit": "迷失在疯狂的利润洪流中",
    "make money! make money! make money!": "挣钱！挣钱！挣钱！",
    "sell it all and make fat stacks! use those stacks to buy cheap shares!": "把它全部卖掉，做大堆！使用这些堆栈购买便宜的股票！",
    "sell those cheap shares at higher prices!! gamble with all of that money!!": "以更高的价格出售那些便宜的股票！！用所有的钱赌博！",
    "the price of trash goes higher and higher": "垃圾的价格越来越高",
    "uhhh basically you should be fracking all the time!": "呃，基本上你应该一直在压裂！",
    "use bear down to make shares work for you!": "使用熊市让股票为您服务！",
    "you can make shares you're selling more expensive or shares you're buying even cheaper": "你可以让你卖的股票更贵，或者你买的股票更便宜",
    "you could even buy a bunch of shares cheap then sell them once the price goes back to normal": "你甚至可以低价买入一堆股票，然后在价格恢复正常后卖出",
    "you should always frack and store up lots of trash before using binsider trading to boost the trash price": "在使用 垃圾箱 交易来提高垃圾价格之前，您应该始终压裂并储存大量垃圾",
    "The human, astonished: \"How grand!\"": "人类惊讶地说：“多么伟大啊！”",
    "There's no trash to sort. Go get some more trash first!": "没有垃圾可以分类。 先去多捡些垃圾吧！",
    "You don't have enough food stored up for new raccoons to join your crew. Stockpile more food!": "你没有足够的食物储备让新浣熊加入你的团队。 多囤点粮！",
    "You'll return and free everyone, stat": "你会回来释放所有人，stat",
    "You Lose...": "你输了...",
    "'money' is half of your name": "“钱”是你名字的一半",
    "(Profits Keep Lifting Me) Higher & Higher": "（利润不断提升我）越来越高",
    "(send the weird image)": "（发送奇怪的图像）",
    "*hi-fiving the studio audience one by one, the applause still thunderous*": "*演播室观众一一击掌，掌声依旧雷鸣*",
    "*opens door*": "*打开门*",
    "*puts on really big shades* only doritos": "*戴上非常大的色调*只有多力多滋",
    "*shouting over the sound of the guillotine blade sharpening* hahaha ok": "*对断头台刀片磨刀的声音大喊*哈哈哈好吧",
    "*studio audience applauds for several minutes straight*": "*演播室观众连续几分钟鼓掌*",
    "*turn to camera 2 for close up* we put doritos in all the vending machines": "*转向摄像机 2 进行特写*我们将多力多滋放入所有自动售货机",
    "A crude fix for the current problem, but tasty nonetheless.": "对当前问题的粗略修复，但仍然很好吃。",
    "a paper umbrella just came out of me": "一把纸伞刚从我身上出来",
    "A Teacher is too exhausted to communicate at this time": "老师此时太累了无法交流",
    "absolutely no butt": "绝对没有屁股",
    "Ah heresy is it?": "是异端啊？",
    "All of the figurines on my shelves are stories.": "我架子上的所有小雕像都是故事。",
    "allow me to barf more in your stead": "让我代替你吐更多",
    "Allow me to list some of the highlights of this exciting new education center.": "请允许我列出这个令人兴奋的新教育中心的一些亮点。",
    "alright that’s enough": "好吧，这就够了",
    "also lmao at duty": "也值班",
    "always? we like just recently gained sapience": "总是？我们喜欢刚刚获得的智慧",
    "an ever present posterior in service of my lord": "为我的主服务的永远存在的后勤人员",
    "and how is school money different?": "学校的钱有什么不同？",
    "and i really need your input here": "我真的需要你在这里输入",
    "and if anyone texts over 55 words they will explode!!!": "如果有人发短信超过 55 个字，他们会爆炸！！！",
    "and if you don't fund my schools it will explode": "如果你不资助我的学校，它就会爆炸",
    "and it honestly sucks": "老实说，这很糟糕",
    "and my butt sits on The Remainder only for you": "我的屁股只为你坐在余下",
    "And no, I display them.": "不，我展示它们。",
    "and now everyone is acting soooo serious": "现在每个人都表现得很认真",
    "and paying teachers": "和付钱给老师",
    "and reading what too many other fans think can make you feel ashamed or disgusted.": "阅读太多其他粉丝的想法会让你感到羞愧或厌恶。",
    "and sleep specialists.": "和睡眠专家。",
    "and that's ok too!": "这也没关系！",
    "and that’s fun?": "这很有趣吗？",
    "and the money from me will trickle down": "我的钱会涓涓细流",
    "and the other one is happy": "另一个很开心",
    "and you don’t play with them at all?": "你根本不和他们一起玩吗？",
    "and your family is super rich": "你家超级有钱",
    "any problem can be handled by saying 'this rules'": "任何问题都可以通过说“这条规则”来解决",
    "anyone could afford a jet ski if they wanted": "如果他们愿意，任何人都可以买得起摩托艇",
    "anyone could save up for a jet ski": "任何人都可以为摩托艇存钱",
    "anything my liege": "任何我的君主",
    "anyway my school is like totally out of money": "反正我的学校完全没钱了",
    "Anyway, no big deal!": "总之，没什么大不了的！",
    "are we even paying everyone enough to afford them?": "我们甚至付给每个人足够的钱来负担​​他们的费用吗？",
    "are you in all of my phone conversations?": "你在我所有的电话交谈中吗？",
    "Are you receiving my messages?": "你收到我的消息了吗？",
    "As a professional and as your active enemy, I refuse.": "作为专业人士和你的敌人，我拒绝。",
    "as i shoot it randomly upon others": "当我随意向其他人射击时",
    "as you command": "如你所愿",
    "as you wish sire": "如你所愿，陛下",
    "at least my jokes are good": "至少我的笑话很好",
    "auction went well?": "拍卖顺利吗？",
    "awesome!": "惊人的！",
    "big jet ski party this weekend": "这个周末的大型喷气滑雪派对",
    "big news fam...": "大新闻家庭...",
    "booooooooooom": "呜呜呜",
    "but do not turn so far away from The Remainder that you lose its stench": "但不要从 The Remainder 转得太远，以免失去它的恶臭",
    "but engines are replaceable and the thrill of racing lasts forever": "但引擎是可更换的，赛车的快感永远持续",
    "but it's not our problem": "但这不是我们的问题",
    "but like everyone is ok right": "但就像每个人都很好",
    "but like where and when": "但喜欢何时何地",
    "But no worries. I've got some ideas!": "但不用担心。我有一些想法！",
    "but not my money gun of course!": "但当然不是我的钱枪！",
    "but they are not allowed direct contact": "但不允许他们直接接触",
    "but this is still automated text": "但这仍然是自动文本",
    "but would that fix anything?": "但这能解决什么问题吗？",
    "but wow i hated all of that": "但哇，我讨厌这一切",
    "but, to be clear, not doctors or teachers": "但是，要明确的是，不是医生或老师",
    "by the laws of The Remainder": "根据剩余的法律",
    "by who?!?!": "由谁？！？！",
    "bye Ding Dong": "再见叮咚",
    "c'mon! be cool": "来吧！冷静点",
    "Can I be bluntly honest with you?": "我可以坦率的跟你说实话吗？",
    "can we bring this up in the next group meeting?": "我们可以在下一次小组会议上提出这个吗？",
    "can you send me the details so i can look them over again?": "你能把细节发给我，让我再看一遍吗？",
    "can't remember the name": "不记得名字",
    "Climate Climax": "气候高潮",
    "come on teach this isn't funny": "来教这不好笑",
    "Come on. Sincerely, I'm really sorry. I don't want TK to miss out on this info because of me.": "来吧。真诚的，我真的很抱歉。我不希望 TK 因为我而错过这些信息。",
    "Commendable job.": "值得称赞的工作。",
    "congrats everyone": "恭喜大家",
    "Cool!": "凉爽的！",
    "could i watch with you sometime?": "我可以和你一起看吗？",
    "Could you grab some Kissma Lotion?": "你能拿一些 Kissma 乳液吗？",
    "countdown just hit zero": "倒计时刚刚打到零",
    "countdown to your butt detaching via explosive force": "通过爆发力分离你的臀部倒计时",
    "dang it too late": "为时已晚",
    "dark humor i love it": "黑色幽默我喜欢",
    "definitely not going to 'go die'": "绝对不会“去死”",
    "Dermatology": "皮肤科",
    "Detestable fools, both of you.": "可恶的傻瓜，你们俩。",
    "Did anyone pack sunscreen or ibuprofen?": "有人带防晒霜或布洛芬吗？",
    "did you just not want to?": "你只是不想吗？",
    "did you sign off on these?": "你在这些上签字了吗？",
    "did you spend five minutes or five hours on that?": "你花了五分钟还是五个小时？",
    "Ding Dong?": "叮咚？",
    "Do you have any friends you could show it to?": "你有朋友可以展示给你看吗？",
    "do you have this little work to do?": "你有这个小工作要做吗？",
    "do you play with the dolls?": "你玩洋娃娃吗？",
    "do you think i could send it over?": "你觉得我可以寄过去吗？",
    "Doc I do actually need something": "医生我确实需要一些东西",
    "Doc, I'm really sorry. You can list the rest of your stuff or whatever.": "医生，我真的很抱歉。您可以列出其余的东西或其他任何东西。",
    "Does anyone need me to pack any other medical supplies?": "有人需要我打包其他医疗用品吗？",
    "doesn't that wear out the yacht engine": "这不会磨损游艇引擎吗",
    "don't text me anymore": "不要再给我发短信",
    "Don't worry, though: if you get a boring princess you can just pay to try again.": "不过别担心：如果你遇到一个无聊的公主，你可以花钱再试一次。",
    "Double Loss...": "双输...",
    "Double Win!": "双赢！",
    "Dr. Raccoon": "浣熊博士",
    "Duh!": "呸！",
    "EVEN LOOKING AT MONEY DOESN'T FEEL GOOD": "连看钱都感觉不好",
    "everyone types 'uh' first when they're telling the truth": "每个人在说真话时都会先输入“呃”",
    "Ew lmao!": "呜呜呜！",
    "exactly sire": "陛下",
    "excellent question": "很好的问题",
    "Explosive Potential": "爆炸潜力",
    "FINALLY": "最后",
    "Fine. I will begin reading from my list again.": "美好的。我将再次开始阅读我的清单。",
    "first though is there any way you could stop calling me sire": "首先，你有什么办法可以停止叫我陛下",
    "Flies in the Pocket": "口袋里的苍蝇",
    "given enough time": "给予足够的时间",
    "gotta have my doritos": "得吃我的多力多滋",
    "great": "伟大的",
    "great!": "伟大的！",
    "had you considered that surprising me was the least chillaxing option?": "你有没有想过让我吃惊是最不令人毛骨悚然的选择？",
    "Haha OK I can lay down some basics.": "哈哈好吧我可以放下一些基本的。",
    "haha what are we laughing about?": "哈哈，我们在笑什么？",
    "haha yeah it rules": "哈哈，是的，它规则",
    "haha, yeah i bet": "哈哈，是的，我敢打赌",
    "hahahahahahahahahaha": "哈哈哈哈哈哈哈哈哈",
    "Half of the women are ship captains and the other half turn into boats.": "一半的女性是船长，另一半变成了船。",
    "Hangover Blues": "宿醉蓝调",
    "has anyone heard from MB?": "有人听说过MB吗？",
    "Hate to interrupt, chums, but I'd just like to say congratulations all around.": "讨厌打断，伙计们，但我只想对周围的人表示祝贺。",
    "haters to the left!": "左边的仇敌！",
    "have you all been planning this without me": "没有我，你们都在计划吗",
    "Hello!": "你好！",
    "hey": "嘿",
    "hey everyone doc has an \"emergency\"": "嘿，每个医生都有“紧急情况”",
    "hey gang": "嘿，帮派",
    "hey MB i don't remember approving any of these cut fundings or purchases": "嘿 MB 我不记得批准任何这些削减资金或购买",
    "hey teach": "嘿教",
    "hey what’s up?": "嘿，怎么了？",
    "hmmmmmmmm": "嗯嗯嗯嗯",
    "Hold on a second though...": "不过等一下……",
    "honestly they seem pretty upset": "老实说，他们看起来很沮丧",
    "Hooray!!!": "万岁！！！",
    "how bad is it?": "有多糟糕？",
    "how did that happen?": "那是怎么发生的？",
    "How did you find this?": "你是怎么找到这个的？",
    "how though?": "怎么样？",
    "How weird of an image are we talking about?": "我们谈论的图像有多奇怪？",
    "how's everyone else?": "其他人还好吗？",
    "However, I fear for the mental health of those involved in such a study, so I cannot recommend it.": "但是，我担心参与此类研究的人的心理健康，所以我不能推荐它。",
    "huh?": "嗯？",
    "i 'love this'": "我喜欢这个'",
    "i agree": "我同意",
    "I also feel quite ill though.": "不过我也觉得很不舒服。",
    "i also planted a bomb": "我也种了炸弹",
    "i am disappointed but i cannot disobey you lest i too arrive at The Incinerator's fiery doors": "我很失望，但我不能不服从你，以免我也到达焚化炉的火门",
    "i am planning to buy a larger, more powerful butt my liege": "我打算买一个更大，更强大的屁股我的领主",
    "i am texting to make a report": "我正在发短信报告",
    "i apologize but i am duty bound": "我道歉，但我有责任",
    "I assure you that I 'get' very little of what you're doing.": "我向你保证，我对你正在做的事情知之甚少。",
    "I believe Money Baby's profit motive has pushed us too far away from caring for our citizens.": "我相信 Money Baby 的盈利动机已经让我们离关心我们的公民太远了。",
    "I can't hear you idealists over the sound of my money gun": "在我的钱枪声中我听不到你们理想主义者的声音",
    "i cannot sire": "我不能做主",
    "I chose all of the specialties.": "我选择了所有的专业。",
    "I do not agree with this line of reasoning.": "我不同意这种推理。",
    "I do, though when you type it out it seems worse somehow.": "我有，虽然当你把它打出来时，它似乎更糟。",
    "I don't feel good like at all.": "我感觉一点都不好。",
    "i don't really care about that": "我真的不在乎那个",
    "i don't think it's like gross weird or anything": "我不认为这很奇怪或任何东西",
    "I don't think telling you this will help, but I have to try.": "我不认为告诉你这会有帮助，但我必须尝试。",
    "I FEEL AWFUL": "我感觉糟透了",
    "i feel like i have to say this every time you send a message dirt": "我觉得每次你发消息都得这么说",
    "i fell asleep in the cooler we brought": "我在我们带来的冷却器里睡着了",
    "i found a weird image online": "我在网上发现了一张奇怪的图片",
    "i guess i couldn't afford one": "我想我买不起",
    "I guess I've never had my boss over before.": "我想我以前从来没有让我的老板过来过。",
    "i guess not": "我猜不是",
    "i have a question": "我有个问题",
    "i have an announcement": "我有一个公告",
    "i have made myself undignified by partying too much": "我参加太多聚会使自己有失尊严",
    "I have some concerns I wanted to surface.": "我有一些我想表达的担忧。",
    "i heard Money Baby is making changes to the economics textbooks": "我听说 Money Baby 正在修改经济学教科书",
    "i just covered a pizza with money": "我刚用钱盖了一个披萨",
    "i just realized I took a limo to school like every day last month": "我才意识到我像上个月的每一天一样坐豪华轿车去学校",
    "I knocked over my shelf trying to pick out an anime blu ray.": "我打翻了我的架子，试图挑选一部动漫蓝光。",
    "i know things have really sucked": "我知道事情真的很糟糕",
    "i know you're tired": "我知道你累了",
    "i love my butt lol": "我爱我的屁股哈哈",
    "I made a list of car games to play!": "我列出了要玩的汽车游戏！",
    "i made a mix full of only": "我做了一个混合只有",
    "i mean it's a little funny, but mostly weird": "我的意思是这有点好笑，但大多很奇怪",
    "i must consult the scholars": "我必须咨询学者",
    "i need to talk though": "我需要谈谈",
    "i packed only trash, but i've already sniffed all of it. i long to smell the scent of new trash from the car window.": "我只打包了垃圾，但我已经全部闻过了。我渴望从车窗闻到新垃圾的气味。",
    "i planned our route to go by as many trash sites as possible": "我计划我们的路线要经过尽可能多的垃圾场",
    "i put a bomb in everyone's phones": "我在每个人的手机里都放了一颗炸弹",
    "I see, so the show was similar to my proposed medical care expansions.": "我明白了，所以这个节目类似于我提议的医疗保健扩展。",
    "i shall meditate on The Remainder in the meantime": "同时我会冥想剩余部分",
    "i take that as a compliment": "我认为这是一种恭维",
    "i think i'd like to hear from everyone on this": "我想我想听听大家的意见",
    "i think i'm busy that weekend too": "我想我那个周末也很忙",
    "I think we should help them.": "我认为我们应该帮助他们。",
    "i thought that's what i was doing": "我以为这就是我正在做的",
    "I thought you all just joined The Remainder": "我以为你们都刚刚加入了 The Remainder",
    "I thought you just suggested that to be polite.": "我以为你只是建议礼貌。",
    "i thought you knew about all types of online stuff": "我以为你知道所有类型的在线资料",
    "i thought you were ringing the doorbell": "我以为你在按门铃",
    "i was just having fun pretending that i had planted bombs": "我只是假装我埋了炸弹玩得很开心",
    "i will praise The Remainder with my nose": "我会用我的鼻子赞美剩下的人",
    "I would like permission to war with other trash collectors": "我想获准与其他垃圾收集者开战",
    "I would prefer that raccoons be getting the care they need.": "我希望浣熊得到他们需要的照顾。",
    "I would urge everyone to stay hydrated and seek a dark, cool shelter.": "我会敦促每个人保持水分并寻找一个黑暗、凉爽的避难所。",
    "i;m barfin rn": "我;m barfin rn",
    "I'll also add that our hospital could use some funds.": "我还要补充一点，我们医院可以使用一些资金。",
    "i'll bring a bunch of popcorn!": "我会带一堆爆米花！",
    "i'll let the teachers know they're all getting raises": "我会让老师知道他们都在加薪",
    "i'll put you down for next weekend then": "那我让你下周末",
    "i'll talk to MB and see what’s up": "我会和 MB 谈谈，看看发生了什么事",
    "I'm allocating a hefty princess fund for this trip, so go wild.": "我为这次旅行分配了一大笔公主基金，所以去疯狂吧。",
    "i'm allowed to have fun!": "我可以玩得开心！",
    "i'm busy": "我很忙",
    "i'm driving rn anyway": "反正我在开车",
    "I'm going back to work. I've run out of patience.": "我要回去工作了。我已经没有耐心了。",
    "i'm gonna buy a big gun": "我要买一把大枪",
    "i'm gonna party all night yeah yeah yeah": "我要彻夜狂欢",
    "I'm leaving.": "我走了。",
    "i'm looking out for raccoons": "我在寻找浣熊",
    "I'm not actually laughing because that would hurt.": "我实际上并没有笑，因为那会很痛。",
    "i'm not leaving": "我不会离开",
    "i'm not the mayor of your butt": "我不是你屁股的市长",
    "i'm not upset at you": "我不生你的气",
    "i'm out": "我出去了",
    "i'm ready for the report on what's cool these days": "我已经准备好接受关于这些天很酷的报告了",
    "i'm seeing reports that this fixes everything": "我看到报告说这可以解决所有问题",
    "I'M SMART": "我很聪明",
    "I'm sorry to upset you, but it's what I believe.": "很抱歉让你不高兴，但这是我所相信的。",
    "i'm sorry... give me a second to process": "对不起...给我一秒钟的时间来处理",
    "i'm the education advisor doc. i have to help announce this one.": "我是教育顾问医生。我必须帮助宣布这一点。",
    "I'M THE ONE IN CHARGE": "我是负责人",
    "i'm upset too you know": "我也难过你知道",
    "i've never jet skied before": "我以前从来没有玩过喷气式滑水",
    "I’m proud to announce that a new facility to train our medical staff is now operational": "我很自豪地宣布，一个培训我们医务人员的新设施现已投入使用",
    "I’m waiting on an auction to end.": "我正在等待拍卖结束。",
    "if we don't have money, even we can't get medicine": "如果我们没有钱，即使我们也买不到药",
    "if you do it right, it looks a lot like you're trying": "如果你做对了，看起来很像你在尝试",
    "in the beginning, there was no trash": "一开始，没有垃圾",
    "in this way we signal our devotion to The Remainder": "通过这种方式，我们表达了我们对 The Remainder 的热爱",
    "Incinerating Bridges": "焚烧桥梁",
    "Income inequality left unaddressed will naturally worsen and eventually lead to social unrest and even revolution.": "收入不平等得不到解决，自然会恶化，最终导致社会动荡甚至革命。",
    "Intensive care": "重症监护室",
    "is getting a pizza!!!": "正在吃披萨！！！",
    "Is now a good time to chat?": "现在是聊天的好时机吗？",
    "Is that a threat?": "这是威胁吗？",
    "is this another movie plot?": "这是另一个电影情节吗？",
    "is what i bet you'd like to see": "我敢打赌你想看",
    "It absolutely isn't.": "绝对不是。",
    "It can fit several classes at once for valuable demonstrations and lectures from visiting medical faculty.": "它可以同时容纳多个课程，用于访问医学教师的有价值的演示和讲座。",
    "It feels wrong to speak of austerity while living in luxury.": "在生活奢侈的同时谈论紧缩是错误的。",
    "it is not fit to worship": "不适合崇拜",
    "It is quite bad.": "这很糟糕。",
    "it makes me upset": "这让我心烦意乱",
    "it really doesn't seem like you do": "看起来你真的不像",
    "It rewards you with cool new princesses at a variety of percentage chances. Just like gambling!": "它以各种百分比的机会奖励你很酷的新公主。就像赌博一样！",
    "it says so on our yacht racing shirts": "我们的游艇赛车衫上是这么写的",
    "it's a no from me": "我不同意",
    "it's all gone. sorry chief": "一切都过去了。对不起院长",
    "it's just an upsetting thing to think about": "这只是一件令人沮丧的事情",
    "it's much better now": "现在好多了",
    "it's not just you": "不只是你",
    "it's ok to wiggle your butt and also ok not to do that": "可以扭动你的屁股，也可以不那样做",
    "it's the Raccoon Coast now": "现在是浣熊海岸",
    "It’s incredibly fun! I love the thrill of the chase.": "非常有趣！我喜欢追逐的快感。",
    "Jet Ski Legacy": "喷气滑雪遗产",
    "jet skis are egalitarian": "摩托艇是平等主义的",
    "just absolutely not": "绝对不是",
    "just confusing": "只是令人困惑",
    "just read the bugs one of your peer-reviewed articles instead": "只需阅读您的同行评审文章中的错误",
    "just send any problems through Money Baby": "只要通过Money Baby发送任何问题",
    "KISSMA BUTT": "亲吻屁股",
    "l o l": "哈哈",
    "Lead Trash Commandant of The First Order of The Remainder reporting": "剩余报告第一秩序的首席垃圾指挥官",
    "Let's start with this:": "让我们从这个开始：",
    "like everyone in our whole society": "像我们整个社会的每个人一样",
    "like the rabbit with the carrot": "像兔子加胡萝卜",
    "lmao": "囧",
    "lmao calm down": "lma冷静点",
    "lmao good one": "好一个",
    "lmao no": "没有",
    "lmao that banner": "lmao那条横幅",
    "lmao they're really boring is what i'm saying": "我要说的是他们真的很无聊",
    "lmaooooo": "呜呜呜",
    "lol": "哈哈",
    "LOL": "哈哈",
    "makes me feel a little better about my body, which is dying i think": "让我对自己的身体感觉好一点，我认为它正在死去",
    "MAX": "最大",
    "Maxed Out": "超出",
    "maybe": "也许",
    "Medical Drama": "医疗剧",
    "Meeeeeeeeeeeeeeeeeeeeeeeeeee": "啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊",
    "might have to think on this one for a while": "可能需要考虑一段时间",
    "Money Baby said we can’t have more": "钱宝贝说我们不能拥有更多",
    "mostly yourself": "主要是你自己",
    "my bad!": "我的错！",
    "My body is producing trash": "我的身体在制造垃圾",
    "my collectors cannot serve a false ruler": "我的收藏家不能侍奉假统治者",
    "My dedication to medicine is such that I will assist even you.": "我对医学的奉献是这样的，我什至会帮助你。",
    "my new butt awaits": "我的新屁股等待着",
    "no comment": "没有意见",
    "no more money": "没有钱了",
    "No one is dying. That's extreme.": "没有人会死。这太极端了。",
    "no raises yet": "还没有加薪",
    "no sire": "没有陛下",
    "no way!!": "没门！！",
    "No, at this point I would derive no joy from listing the features, even though listing is one of my primary hobbies.": "不，在这一点上，我不会从列出功能中获得乐趣，即使列出是我的主要爱好之一。",
    "No, I will not.": "不我不会。",
    "NO!!": "不！！",
    "No.": "不。",
    "nope": "不",
    "NOT Rhombus Rescue Dancers!": "不是菱形救援舞者！",
    "now i depart": "现在我离开",
    "nvm i don't wanna know": "nvm我不想知道",
    "O": "○",
    "of your phone????": "你的手机？？？",
    "oh bummer": "哦，真可惜",
    "Oh dear god...": "哦，天哪……",
    "Oh haha, right! Sorry!": "哦哈哈，对了！对不起！",
    "oh my god": "我的天啊",
    "Oh neat.": "哦整洁。",
    "oh uh lighten up lol": "哦，哦，轻点，哈哈",
    "oh weird": "哦奇怪",
    "Oh yeah!": "哦耶！",
    "oh yes sire": "哦，是的，陛下",
    "Oh, fun!": "有趣哦！",
    "Oh, Money Baby, you beat me to it. But you've erroneously included quotes.": "哦，金钱宝贝，你打败了我。但是您错误地包含了引号。",
    "Oh, was it fun when you bought the network that owns Basketball Sparklers and canceled it?": "哦，当你购买了拥有 Basketball Sparklers 的网络并取消它时，这很有趣吗？",
    "Oh...I guess that's one way to start a conversation!": "哦...我想这是开始对话的一种方式！",
    "Ohhhhhhh": "哦哦哦",
    "ok 'cool'": "嗯不错'",
    "ok but what did you want?": "好的，但你想要什么？",
    "OK great!": "好，很好！",
    "ok i get it": "好的我明白了",
    "ok looking forward to a rigorous debate!": "好的，期待激烈的辩论！",
    "ok now i'm having fun": "好的，现在我很开心",
    "ok ok ok ok ok": "好的 好的 好的 好的 好的",
    "ok ok ok ok what's up": "好的 好的 好的 好的 怎么了",
    "ok so... *dramatic pause*": "好吧... *戏剧性的停顿*",
    "ok sure": "好的",
    "ok that's it": "好的，就是这样",
    "ok things seem a little tense so i just sent out pizzas for everyone!": "好吧，事情似乎有点紧张，所以我只是给大家送了披萨！",
    "ok this is epic": "好的，这是史诗",
    "ok well take more money then": "好吧，那就多花点钱",
    "ok, so you were delivering a report right?": "好的，所以你是在提交报告，对吗？",
    "OK... sure! Hit me with it!": "好的！用它打我！",
    "On to my topic of discussion though: I've seen medical costs steadily rising lately.": "不过，关于我的讨论主题：我最近看到医疗费用稳步上升。",
    "Oncology": "肿瘤学",
    "one raccoon is upset": "一只浣熊不高兴",
    "one request": "一个请求",
    "one, take it down several notches": "一、把它降低几个档次",
    "online": "在线的",
    "only fifty left": "只剩五十个",
    "Ophthalmology": "眼科",
    "or any other raccoons who helped make the money": "或任何其他帮助赚钱的浣熊",
    "other species handle The Remainder but do not obey our laws": "其他物种处理剩余物但不遵守我们的法律",
    "Please just let me finish this quickly.": "请让我快点完成。",
    "please just respond normally": "请正常回复",
    "please please calm down with this stuff": "请用这些东西冷静下来",
    "please reach out at a later date": "请稍后联系",
    "please send all the greasy, crumb-filled boxes to my shrine": "请把所有油腻腻的、装满面包屑的盒子送到我的神社",
    "please tell me more": "请告诉我更多",
    "pop those bottles little baby raccoons": "弹出那些瓶子小浣熊宝宝",
    "pretty long name": "好长的名字",
    "Renal medicine": "肾内科",
    "repeat until the pain goes away": "重复直到疼痛消失",
    "ROAD TRIP READY RADIO JAMS": "适合公路旅行的无线电堵塞",
    "Road Trip!": "公路旅行！",
    "Roooooaaaaaaad triiiiiiiiip!!!": "哇哇哇哇哇哇哇哇哇哇哇哇！！！",
    "s": "s",
    "Sailor Don't Sink Her is an anime about a group of powerful women in an intergalactic navy.": "Sailor Don't Sink Her 是一部关于星际海军中一群强大女性的动漫。",
    "same...": "相同的...",
    "seasons are how tv shows separate themselves": "季节是电视节目如何区分自己",
    "see everyone this is fun": "看到大家这很有趣",
    "See You in the Funny Pictures": "搞笑图片见",
    "seems like a luxury": "似乎是一种奢侈",
    "seems pretty simple honestly": "老实说，看起来很简单",
    "seriously fund my schools": "认真资助我的学校",
    "seriously?": "严重地？",
    "Shelf Life": "保质期",
    "shoot": "射击",
    "shut up!!!": "住口！！！",
    "since this time, the faithful have worshiped the refuse": "从那时起，信徒们开始崇拜垃圾",
    "sire i have a request": "陛下，我有一个要求",
    "sire, no!": "陛下，不！",
    "Skateboarding in a graveyard!!": "在墓地滑板！！",
    "so anyway you can't just assume people can afford jet skis": "所以无论如何你不能只是假设人们买得起摩托艇",
    "So I try to just like what I like and seek out fair criticisms from places I trust.": "所以我试着喜欢我喜欢的东西，并从我信任的地方寻求公平的批评。",
    "so my brain is just like \"WOW big\"": "所以我的大脑就像“哇大”",
    "so some of them can't afford medicine?": "所以有些人买不起药？",
    "so two requests then": "所以有两个请求",
    "So we made money by taking it from the humans, right?": "所以我们是通过从人类那里获取钱来赚钱的，对吧？",
    "so we're going to the beach?": "所以我们要去海滩？",
    "so you want to start a holy trash war?": "所以你想开始一场神圣的垃圾战争？",
    "So, our new operating theater is second to none.": "所以，我们的新手术室是首屈一指的。",
    "Sometimes I just wanna zone out and watch SDSH though": "有时我只是想出去看看 SDSH",
    "soon all will see The Remainder's glory reflected in its image": "很快，所有人都会看到《余留者》的荣耀反映在其形象中",
    "sorry": "对不起",
    "sorry i was away from my phone grabbing a snack": "抱歉，我离开手机拿零食",
    "Sorry, I fell asleep briefly while typing.": "对不起，我在打字的时候睡着了。",
    "sounds good": "听起来不错",
    "spread that wealth around like butter": "像黄油一样散布财富",
    "stoooooopppppp": "呜呜呜呜呜呜",
    "STOP IT NOW OR YOU'RE FIRED": "立即停止，否则您将被解雇",
    "Submarine-chan is a woman who turns into a submarine. She's the fan favorite.": "潜艇酱是一个变成潜艇的女人。她是粉丝的最爱。",
    "Such is the depth of your density.": "这就是你们密度的深度。",
    "sure": "当然",
    "sure what's up doc": "确定怎么了医生",
    "Sure, I guess I could think of it that way.": "当然，我想我可以这样想。",
    "Sure, I trust that you've seen this rabbit and enjoyed its antics.": "当然，我相信您已经看过这只兔子并喜欢它的滑稽动作。",
    "Sure. I have some other research I want to present as well.": "当然。我还有一些其他的研究我想介绍。",
    "technically if they didn't buy things like food or housing": "从技术上讲，如果他们不购买食物或住房之类的东西",
    "tell them to stop": "告诉他们停止",
    "tell TK about the vending machines!!": "告诉 TK 自动售货机！",
    "Tendon research": "肌腱研究",
    "Textbook Avoidance Tactics": "教科书回避策略",
    "thank you for reaching out to A Teacher": "感谢您与老师联系",
    "thanks Dirt": "谢谢污垢",
    "thanks for clarifying": "感谢您的澄清",
    "Thanks.": "谢谢。",
    "That is correct. Medicine has gotten far too expensive recently.": "那是对的。最近的药太贵了。",
    "that just shoots money!!!": "那只是射钱！",
    "that number is way too large to conceptualize": "这个数字太大了，无法概念化",
    "that show wasn't profitable at all": "那个节目根本没有盈利",
    "that sounds wrong": "听起来不对",
    "That would be one solution, but there's no way to force them to right now.": "那将是一种解决方案，但现在没有办法强迫他们这样做。",
    "that... sounds bad": "那……听起来很糟糕",
    "that's five words!": "那是五个字！",
    "that's how you lose money": "这就是你赔钱的方式",
    "that's just for me": "那只是为了我",
    "that's the game": "这就是游戏",
    "the bomb is in your butt": "炸弹在你的屁股里",
    "The Coolest Ranch Possible": "最酷的牧场",
    "the Cotton Candy Cleaner": "棉花糖清洁剂",
    "The emergency is very real and not a contrivance of my own.": "紧急情况非常真实，不是我自己的发明。",
    "The gelatin shots were not wise. Who distributed those?": "明胶镜头并不明智。谁分发的？",
    "the humans in power stole everything they had anyway, so it's a fair game": "掌权的人类无论如何都偷走了他们所拥有的一切，所以这是一场公平的游戏",
    "The Incinerator isn't real! None of this is!": "焚化炉不是真的！这些都不是！",
    "The Incinerator waits for us all, thus we must obey": "焚化炉等着我们所有人，因此我们必须服从",
    "The main one is a cool new game on my phone.": "主要的是我手机上的一款很酷的新游戏。",
    "the one true trash master": "真正的垃圾大师",
    "the other collectors also call you sire": "其他收藏家也称你为先生",
    "THE PROPHET WHO BROUGHT US OUT FROM UNDER THE HEEL OF THE TRASH CREATORS": "从垃圾制造者的脚跟下把我们带出来的先知",
    "then, someone threw something away": "然后，有人扔了东西",
    "There are a lot of raccoons who are not doing great.": "有很多浣熊做得不好。",
    "There's a controversy with this new third season.": "这个新的第三季存在争议。",
    "There's an emergency everyone!": "大家有紧急情况！",
    "they are destined for The Incinerator regardless, but we can hasten their arrival": "无论如何，他们注定要前往焚化炉，但我们可以加快他们的到来",
    "they lost and i don't have time to care about every loser species": "他们输了，我没有时间关心每一个失败者物种",
    "they spell DORITOS": "他们拼写 DORITOS",
    "They were also shut down for lack of profit.": "他们也因缺乏利润而被关闭。",
    "They. Are. Figurines.": "他们。是。小雕像。",
    "They’re successful hunts.": "他们是成功的狩猎。",
    "this automated message is here to inform you that A Teacher is unavailable": "此自动消息是为了通知您老师不可用",
    "This is a waste of time. I skipped my lunch for this!": "这是浪费时间。我为此跳过了午餐！",
    "this is automated laughter hahahahahahaha": "这是自动笑哈哈哈哈哈哈",
    "this is economics": "这是经济学",
    "this is freaking me out": "这把我吓坏了",
    "THIS IS THE WORST": "这是最糟糕的",
    "this sounds really legit": "这听起来很合法",
    "Though there's really no evidence it was due to censorship and a lot of the season 3 changes were common fan requests.": "尽管确实没有证据表明这是由于审查制度造成的，而且第 3 季的许多变化都是粉丝的常见要求。",
    "TK we'll take this to our private chat": "TK 我们会把这个带到我们的私人聊天室",
    "To be clear.": "要清楚。",
    "Trillion Dollar Tussle": "万亿美元之争",
    "two, let’s take, like... a break from texting each other": "二，让我们休息一下，就像...休息一下互相发短信",
    "ugh nevermind it's not even worth it": "呃，没关系，这甚至不值得",
    "ugh, wait": "呃，等等",
    "ughhhhh": "啊啊啊",
    "uh oh yeah no problem": "哦哦是的没问题",
    "Uhhh sure!": "嗯，确定！",
    "uhhhh i have no idea really. it doesn't make sense to me at least.": "呃，我真的不知道。至少对我来说没有意义。",
    "Uhhhh just figurines from Sailor Don’t Sink Her: Trapezoid Transformation Era.": "Uhhhh 只是水手不要沉没她的小雕像：梯形转型时代。",
    "unfortunately it's not quite as simple as handing out money": "不幸的是，这并不像分发钱那么简单",
    "uuugh": "呜呜",
    "Vive la révolution": "革命万岁",
    "WAHHHHHHHHOOOOOOOOOO": "哇哦哦哦哦哦哦哦哦哦哦哦哦哦哦哦哦哦哦哦哦哦哦哦哦哦哦哦哦哦哦哦~",
    "Wahooo!!": "哇哦！！",
    "watching a lot of awful people shout at each other on TV": "在电视上看到很多可怕的人互相大喊大叫",
    "we are all in a constant march towards a state of trash": "我们都在不断走向垃圾状态",
    "We have a large number of new, specialized training wings for:": "我们有大量新的、专门的培训部门，用于：",
    "we have a very important hierarchy": "我们有一个非常重要的层次结构",
    "we have fully automated the trash production line": "我们已经完全自动化了垃圾生产线",
    "we have improved trash": "我们改进了垃圾",
    "we have to make rules so we're giving out as little money as possible": "我们必须制定规则，以便我们尽可能少地发放资金",
    "We just all drank far too much on that trip.": "那次旅行我们都喝得太多了。",
    "we need funding and we're sick of your bad jokes": "我们需要资金，我们厌倦了你的坏笑话",
    "we renamed the whole coast after us": "我们以我们的名字重新命名了整个海岸",
    "we used it on books and fixing up the school": "我们把它用在书本上并修整学校",
    "we want to keep the money": "我们想留着钱",
    "we wanted to surprise you": "我们想给你一个惊喜",
    "we were doing so well": "我们做得很好",
    "we would all risk The Incinerator for this transgression": "我们都会为这种违法行为冒着焚化炉的风险",
    "we're already the dominant species on the planet": "我们已经是这个星球上的主导物种",
    "We're going on a road trip!": "我们要去公路旅行了！",
    "we're going to the raccoon coast to chill dude": "我们要去浣熊海岸冷静一下",
    "we're racing yachts": "我们在赛艇",
    "We're still making lots of money, but some people aren't doing so well.": "我们仍然赚了很多钱，但有些人做得并不好。",
    "we've always had them in my family": "我们一直都有他们在我的家人",
    "we've made one trillion dollars!!!!": "我们赚了一万亿美元！！！！",
    "we’re all out of school money": "我们都没有上学的钱",
    "Well I think being a fan is very weird": "嗯，我觉得当粉丝很奇怪",
    "Well the original creator left and fans speculated it was because of censorship because a lot of outfits got redesigns, specifically Submarine-chan's outfit.": "好吧，最初的创作者离开了，粉丝们猜测这是因为审查制度，因为很多服装都进行了重新设计，特别是 Submarine-chan 的服装。",
    "what about a friend?": "朋友呢？",
    "What about bug spray?": "杀虫剂呢？",
    "what do you collect": "你收集了什么",
    "what do you know?": "你知道什么？",
    "what do you think about all of it?": "你怎么看这一切？",
    "what happened?": "发生了什么？",
    "What happens to them now?": "他们现在怎么样了？",
    "what if other people with more money helped?": "如果其他有钱的人帮忙怎么办？",
    "What is Kissma?": "什么是Kissma？",
    "What shall I bring?": "我要带什么？",
    "what size are you?": "你是几码？",
    "what?": "什么？",
    "What?": "什么？",
    "what's funny?": "有什么好笑的？",
    "what's going on": "这是怎么回事",
    "What's Left Is The Remainder": "剩下的就是余数",
    "what's the controversy?": "有什么争议？",
    "what’s cool these days?": "这几天有什么好喝的？",
    "whatever nbd": "随便 nbd",
    "when you put it like that": "当你这样说",
    "where did the money go": "钱都去哪儿了",
    "where those who have sinned against The Remainder go once this life is done": "一旦这一生结束，那些对剩余者犯罪的人会去哪里",
    "which allows more time for worship": "这样可以有更多的时间来敬拜",
    "who could possibly be against that?": "谁能反对呢？",
    "whoa! calm down! this is getting out of hand": "哇！冷静下来！这已经失控了",
    "wiggling my butt rn": "扭动我的屁股",
    "wish i felt as good as i look in that pic": "希望我感觉和我在这张照片中看到的一样好",
    "woooo!!!!": "呜呜！！！！",
    "wooooooooo": "呜呜呜",
    "woop woop!": "呜呜！",
    "wow thanks": "哇谢谢",
    "yeah not feeling great here either": "是的，这里也感觉不好",
    "yeah that sounds nice": "是的，听起来不错",
    "yeah we just bought Florida and we're celebrating": "是的，我们刚买了佛罗里达，我们正在庆祝",
    "yeah whatever": "好吧，无所谓了",
    "yeah! see doc gets it": "是的！看医生明白了",
    "yes but i'm a raccoon": "是的，但我是浣熊",
    "yes it does": "是的，它确实",
    "yes it’s the title given to me by other trash collectors": "是的，这是其他垃圾收集者给我的头衔",
    "yes of course": "当然是",
    "yes sire": "是的，陛下",
    "YES YES YES YES YES YES": "是 是 是 是 是 是",
    "yes, i got that part": "是的，我得到了那部分",
    "yes, it is a place of eternal fire and pain": "是的，这是一个永恒的火焰和痛苦的地方",
    "Yes! My collection is so close to being halfway done!": "是的！我的收藏已经接近完成一半了！",
    "you are ever so wise sire": "你真是太聪明了，陛下",
    "You are so dense that it is almost worthy of study.": "你如此密集，几乎值得研究。",
    "you are so wise": "你真聪明",
    "you are the mayor of my butt sire": "你是我屁股的市长",
    "You better FREAKIN believe it did!!": "你最好是 FREAKIN 相信它做到了！",
    "you can mess up so bad that doesn't happen?": "你能把事情搞得这么糟糕以至于不会发生吗？",
    "you definitely signed off on them": "你肯定签署了他们",
    "you idiot": "你个傻冒",
    "you in?": "你呢？",
    "You just answered to the name Ding Dong!!": "你刚刚回答了叮咚这个名字！！",
    "you need to chillax so bad": "你需要放松一下",
    "you should all just stop": "你们都应该停下来",
    "You wash and it's gone; dang, that's rough": "你洗了，它就不见了； dang，这很粗糙",
    "you were like the only one watching": "你就像唯一一个在看的人",
    "You... might be surprised.": "你……可能会感到惊讶。",
    "you're just like a bank that talks": "你就像一个会说话的银行",
    "you're kidding right?": "你开玩笑的对吧？",
    "You're play-acting old action movies but I can't watch my beautiful basketball princes!!": "你在演老动作片，但我不能看我美丽的篮球王子！！",
    "you're the only one who does it": "你是唯一一个这样做的人",
    "you're the weirdest": "你是最奇怪的",
    "YOU’RE SO STUPID!": "你真糊涂！",
    "you’re such a moron": "你真是个白痴",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "Looking for some other self-motivated and self-actualized raccoons to gather boxes from the trash sortings to build houses. Everyone wants them! So I think it would be nice and fun to build them for everyone. I have seen humans do this and then drink from cans to celebrate. Let’s plan to drink from cans afterwards.": "寻找其他一些自我激励和自我实现的浣熊，从垃圾分类中收集盒子来建造房屋。 每个人都想要他们！ 所以我认为为每个人构建它们会很有趣。 我见过人类这样做，然后从罐头里喝水庆祝。 让我们计划之后用罐头喝。",
    "We've finally cleared the landfill closest to the trees! Having a raging party there tonight, just like we used to have. Bring your own food and trash. We’ve got a lot of chips, maybe bring some desserts I guess? Or drinks or whatever. We’re just happy to have you! Don’t forget your party attitude, wooo! Randy, disregard this message.": "我们终于清除了离树木最近的垃圾填埋场！ 今晚在那里举行一场盛大的派对，就像我们以前一样。 自带食物和垃圾。 我们有很多薯条，也许我想带些甜点吧？ 或者饮料什么的。 我们很高兴有你！ 不要忘记你的派对态度，哇！ 兰迪，忽略这条信息。",
    "Anyway, I think we should all get together and bury more food and see what happens. Maybe we could even section out some unused land specifically for this purpose. My mind is really buzzing with ideas. I’d love for someone to just come hang out by my food growths and chat with me about all of this.": "不管怎样，我认为我们都应该聚在一起，埋下更多的食物，看看会发生什么。 也许我们甚至可以专门为此目的划出一些未使用的土地。 我的脑海里真的充满了想法。 我很想有人来看看我的食物生长情况，和我聊聊这一切。",
    "This is an announcement for all raccoons in the community. Last Saturday, as I was messing around burying stuff for fun, I noticed that some of the food I buried a while ago was growing something. Get this, it was growing NEW FOOD! I know, right?!!": "这是社区中所有浣熊的公告。 上周六，当我为了好玩而到处埋东西时，我注意到我前一段时间埋的一些食物正在长出一些东西。 得到这个，它正在生长新的食物！ 我知道，对吧？！！",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "© 2019–2021": "© 2019–2021",
    "Y": "是",
    "v2.1.0": "v2.1.0",
    "o": "",
    "N": "否",
    "es": "",
    "Ctrl": "Ctrl",
    "X": "X",
    "Option": "Option",
    "Tab": "Tab",
    "F": "F",
    "E": "E",
    "Q": "Q",
    "R": "R",
    "S": "S",
    "T": "T",
    "TK": "TK",
    "W": "W",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "\n": "\n",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "Save File ": "保存文件 ",
    "Completed: ": "已完成: ",
    "Cancel Build: ": "取消建造: ",
    "Cooldown – ": "冷却 – ",
    "Active – ": "激活中 – ",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    " remaining": " 剩余",
    " items in queue": " 物品在队列中",
    " ✔️": " ✔️",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^\$([\d\.]+)$/,
    /^\+\$([\d\.]+)$/,
    /^\-\$([\d\.]+)$/,
    /^\+\$([\d\.]+)K$/,
    /^\+\$([\d\.]+)M$/,
    /^\+\$([\d\.]+)T$/,
    /^\+\$([\d\.]+)B$/,
    /^\-\$([\d\.]+)K$/,
    /^\-\$([\d\.]+)M$/,
    /^\-\$([\d\.]+)T$/,
    /^\-\$([\d\.]+)B$/,
    /^\+([\d\.]+)K$/,
    /^\+([\d\.]+)M$/,
    /^\+([\d\.]+)T$/,
    /^\+([\d\.]+)B$/,
    /^\-([\d\.]+)K$/,
    /^\-([\d\.]+)M$/,
    /^\-([\d\.]+)T$/,
    /^\-([\d\.]+)B$/,
    /^\$([\d\.]+)K$/,
    /^\(([\d\.]+)\/([\d\.]+)\)$/,
    /^成本(.+)$/,
    /^\(([\d\.]+)\%\)$/,
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^Sell (.+) Natural Resources Share$/, '出售 $1 份自然资源股份'],
    [/^Sell (.+) Finance Share$/, '出售 $1 份金融股份'],
    [/^Sell (.+) Death Share$/, '出售 $1 份死亡股份'],
    [/^Sell (.+) Culture Share$/, '出售 $1 份文化股份'],
    [/^Bug (.+) Natural Resources Share$/, '购买 $1 份自然资源股份'],
    [/^Bug (.+) Finance Share$/, '购买 $1 份金融股份'],
    [/^Bug (.+) Death Share$/, '购买 $1 份死亡股份'],
    [/^Bug (.+) Culture Share$/, '购买 $1 份文化股份'],
    [/^You have (.+) of these.$/, '你有 $1 这个。'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Roll the Bones now has a (.+) chance of success.$/, '抽取骨头 现在有 $1 的成功率。'],
    [/^You own (.+) out of (.+) shares \((.+) market share\).$/, '您拥有 $1 \/ $2 股（$3 的市场份额）。'],
    [/^Your (.+) raccoons will eat (.+) food in (.+) second. Make sure you have enough food on hand. Hungry raccoons can't work quickly and new raccoons won't join a community that has no food.$/, '你的 $1 只浣熊将在 $3 秒内吃掉 $2 食物。 确保手头有足够的食物。 饥饿的浣熊不能快速工作，新的浣熊不会加入没有食物的社区。'],
    [/^Your (.+) raccoons will eat (.+) food in (.+) seconds. Make sure you have enough food on hand. Hungry raccoons can't work quickly and new raccoons won't join a community that has no food.$/, '你的 $1 只浣熊将在 $3 秒内吃掉 $2 食物。 确保手头有足够的食物。 饥饿的浣熊不能快速工作，新的浣熊不会加入没有食物的社区。'],
    [/^It's the gang. Right now, ([\d\.]+) out of ([\d\.]+) are doing stuff, and ([\d\.]+) are chilling. New raccoons arrive in ([\d\.]+) seconds.$/, '这是帮派。现在，$1 \/ $2 的人在做事情，而 $3 人则令人毛骨悚然。新的浣熊在 $4 秒内到达。'],
    [/^Some more raccoons are coming this way! They'll be here in (\d+) seconds. Make sure there's enough space available for them to settle in.$/, '更多的浣熊正朝这边来！ 他们将在 $1 秒内到达。 确保有足够的空间供他们安顿下来。'],
    [/^\+(\d+) raccoons arrived$/, '\+$1 浣熊到达'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
    [/^Recruit (.+) Raccoons$/, '招募 $1 只浣熊'],
	[/^Scenario (\d+) of (\d+)$/, '场景 $1 \/ $2'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);